ALTER TABLE "Match"
  ADD COLUMN IF NOT EXISTS "firstHalfStartSeconds" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "firstHalfEndSeconds" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "secondHalfStartSeconds" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "secondHalfEndSeconds" DOUBLE PRECISION;

ALTER TABLE "PlayerAction"
  ALTER COLUMN "period" DROP DEFAULT,
  ALTER COLUMN "period" DROP NOT NULL;
