"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { Archive, ArrowLeft, ChevronLeft, ChevronRight, Clock3, FileVideo, Loader2, Pause, Pencil, Play, Trash2, Upload, UserRound, X } from "lucide-react";
import JSZip from "jszip";
import { actionTypeByKey, actionsForPlayer, type ActionType } from "@/lib/action-types";
import { downloadBlob, exportActionClip, safe } from "@/lib/action-video-export";
import { isExportPickerCancellation, pickExportDirectory, toCsv, writeBlobToDirectory } from "@/lib/export-directory";
import type { ActionRecord, MatchDetail, PlayerRecord } from "@/lib/domain";
import { apiFetch } from "@/lib/http";
import { getRememberedMatchVideo, rememberMatchVideo } from "@/lib/local-video-store";
import { formatTime, roundTime } from "@/lib/time";
import { playerPositionLabel } from "@/lib/player-positions";
import { Pitch, type Coordinate } from "@/components/pitch";
import { Badge, Button, Label, Panel, TextArea } from "@/components/ui";

type PendingAction = { player: PlayerRecord; eventTimeSeconds: number };
export function AnalysisWorkspace({ matchId }: { matchId: string }) {
  const videoRef = useRef<HTMLVideoElement | null>(null); const fileRef = useRef<HTMLInputElement | null>(null);
  const [match, setMatch] = useState<MatchDetail | null>(null); const [sourceUrl, setSourceUrl] = useState<string | null>(null); const [duration, setDuration] = useState(0); const [currentTime, setCurrentTime] = useState(0); const [playing, setPlaying] = useState(false); const [rate, setRate] = useState(1); const [pending, setPending] = useState<PendingAction | null>(null); const [editing, setEditing] = useState<ActionRecord | null>(null); const [filterPlayerId, setFilterPlayerId] = useState("all"); const [previewEnd, setPreviewEnd] = useState<number | null>(null); const [notice, setNotice] = useState<string | null>(null); const [exporting, setExporting] = useState(false); const [exportStatus, setExportStatus] = useState("");
  const load = useCallback(async () => { try { setMatch(await apiFetch<MatchDetail>(`/api/matches/${matchId}`)); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not load the match."); } }, [matchId]);
  useEffect(() => { void load(); getRememberedMatchVideo(matchId).then((file) => { if (file) setSourceUrl(URL.createObjectURL(file)); }).catch(() => undefined); }, [load, matchId]);
  useEffect(() => () => { if (sourceUrl) URL.revokeObjectURL(sourceUrl); }, [sourceUrl]);

  async function chooseVideo(file?: File) { if (!file) return; if (sourceUrl) URL.revokeObjectURL(sourceUrl); const url = URL.createObjectURL(file); setSourceUrl(url); await rememberMatchVideo(matchId, file).catch(() => undefined); const probe = document.createElement("video"); probe.preload = "metadata"; probe.src = url; await new Promise<void>((resolve, reject) => { probe.onloadedmetadata = () => resolve(); probe.onerror = () => reject(new Error("Could not read the video.")); }); await apiFetch(`/api/matches/${matchId}/video`, { method: "PUT", body: JSON.stringify({ fileName: file.name, fileSize: file.size, durationSeconds: probe.duration, mimeType: file.type || "video/mp4", lastModified: new Date(file.lastModified).toISOString() }) }); setDuration(probe.duration); await load(); setNotice("Video selected. The file remains on this device."); }
  function seekTo(seconds: number) { const video = videoRef.current; if (!video) return; const next = Math.max(0, Math.min(duration || video.duration || 0, seconds)); video.currentTime = next; setCurrentTime(next); }
  function tagPlayer(player: PlayerRecord) { if (!sourceUrl) return setNotice("Select this match video first."); const eventTimeSeconds = roundTime(videoRef.current?.currentTime ?? currentTime); videoRef.current?.pause(); setPending({ player, eventTimeSeconds }); }
  function preview(action: ActionRecord) { const video = videoRef.current; if (!video) return setNotice("Select the video again to play this clip."); setPreviewEnd(action.endTimeSeconds); video.currentTime = action.startTimeSeconds; void video.play(); }
  async function removeAction(action: ActionRecord) { if (!confirm(`Delete ${displayAction(action)} by ${action.player.name}?`)) return; await apiFetch(`/api/actions/${action.id}`, { method: "DELETE" }); setMatch((current) => current ? { ...current, playerActions: current.playerActions.filter((item) => item.id !== action.id) } : current); }
  async function exportActions() {
    if (!match?.playerActions.length || exporting) return;
    const file = await getRememberedMatchVideo(match.id).catch(() => null);
    if (!file) return setNotice("Select the local match video before exporting clips.");
    let directory = null;
    try {
      directory = await pickExportDirectory();
    } catch (error) {
      if (isExportPickerCancellation(error)) return;
      return setNotice(error instanceof Error ? error.message : "Could not open the export folder.");
    }
    setExporting(true);
    setNotice(null);
    const matchName = `${match.club.name} vs ${match.opponentClub.name}`;
    const root = `${safe(matchName)}-${match.playerActions.length}-clips`;
    const zip = directory ? null : new JSZip();
    const rows = [["player", "action", "event", "start", "end", "file"]];
    try {
      for (const [index, action] of match.playerActions.entries()) {
        setExportStatus(`Exporting ${index + 1} of ${match.playerActions.length}: ${action.player.name}`);
        const actionName = displayAction(action);
        const result = await exportActionClip(file, { ...action, actionName }, matchName, (status) => setExportStatus(`${index + 1}/${match.playerActions.length} · ${status}`));
        const path = `${safe(action.player.name)}/${safe(actionName)}/${String(index + 1).padStart(3, "0")}-${result.fileName}`;
        if (directory) await writeBlobToDirectory(directory, `${root}/${path}`, result.blob);
        else zip?.file(`${root}/${path}`, result.blob);
        rows.push([action.player.name, actionName, formatTime(action.eventTimeSeconds), formatTime(action.startTimeSeconds), formatTime(action.endTimeSeconds), path]);
      }
      const csv = new Blob([toCsv(rows)], { type: "text/csv;charset=utf-8" });
      if (directory) await writeBlobToDirectory(directory, `${root}/index.csv`, csv);
      else {
        zip?.file(`${root}/index.csv`, csv);
        setExportStatus("Creating ZIP file…");
        downloadBlob(await zip!.generateAsync({ type: "blob", compression: "STORE", streamFiles: true }, (metadata) => setExportStatus(`Creating ZIP file: ${Math.round(metadata.percent)}%`)), `${root}.zip`);
      }
      setNotice(`${match.playerActions.length} clips exported successfully${directory ? ` to ${root}` : " in a ZIP file"}.`);
    } catch (error) {
      setNotice(error instanceof Error ? error.message : "Could not export the clips.");
    } finally {
      setExporting(false);
      setExportStatus("");
    }
  }
  if (!match) return <Panel className="p-8 text-center text-slate-400">{notice || "Loading analysis…"}</Panel>;
  const filtered = filterPlayerId === "all" ? match.playerActions : match.playerActions.filter((action) => action.playerId === filterPlayerId); const timelineDuration = duration || match.video?.durationSeconds || Math.max(1, ...match.playerActions.map((action) => action.endTimeSeconds));
  return <div className="analysis-layout space-y-4"><input ref={fileRef} type="file" accept="video/*" className="hidden" onChange={(event) => void chooseVideo(event.target.files?.[0])}/>
    <header className="flex flex-col justify-between gap-4 rounded-xl border border-white/10 bg-white/[.045] p-4 lg:flex-row lg:items-center"><div><Link href="/" className="inline-flex items-center gap-1 text-xs text-slate-500 hover:text-white"><ArrowLeft size={13}/>Matches</Link><h1 className="mt-2 text-2xl font-bold text-white">{match.club.name} vs {match.opponentClub.name}</h1><p className="mt-1 text-sm text-slate-500">{match.competition.name}{match.roundName ? ` · ${match.roundName}` : ""}</p></div><div className="flex gap-2"><Button disabled={!match.playerActions.length || exporting} onClick={() => void exportActions()}>{exporting ? <Loader2 size={16} className="animate-spin"/> : <Archive size={16}/>}Export clips</Button><Button onClick={() => fileRef.current?.click()}><Upload size={16}/>{sourceUrl ? "Change video" : "Select video"}</Button></div></header>
    {notice || exporting ? <div role="status" className="fixed bottom-4 right-4 z-50 flex max-w-sm gap-3 rounded-xl border border-cyan-300/25 bg-pitch-950/95 px-4 py-3 text-sm text-cyan-100 shadow-2xl"><span>{exporting ? exportStatus : notice}</span>{!exporting ? <button onClick={() => setNotice(null)}><X size={15}/></button> : null}</div> : null}
    <div className="grid items-start gap-4 xl:grid-cols-[17rem_minmax(0,1fr)_21rem]">
      <Panel className="max-h-[720px] overflow-hidden"><div className="border-b border-white/10 p-3"><Label>Squad</Label><p className="mt-1 text-xs text-slate-500">Click the player at the moment of the action</p></div><div className="grid max-h-[650px] grid-cols-2 gap-2 overflow-y-auto p-2 xl:grid-cols-1">{match.club.players.map((player) => <button key={player.id} onClick={() => tagPlayer(player)} className="player-card flex min-w-0 items-center gap-3 rounded-lg border border-white/10 bg-white/[.035] p-2 text-left transition hover:border-cyan-300/40 hover:bg-cyan-300/10"><PlayerPhoto player={player}/><span className="min-w-0"><span className="block truncate text-sm font-bold text-white">{player.shirtNumber ? `${player.shirtNumber} · ` : ""}{player.name}</span><span className="block truncate text-[11px] text-slate-500">{playerPositionLabel(player.position)}</span></span></button>)}</div></Panel>
      <div className="space-y-4"><Panel className="overflow-hidden"><div className="relative aspect-video bg-black">{sourceUrl ? <video ref={videoRef} src={sourceUrl} className="h-full w-full" playsInline onLoadedMetadata={(event) => { setDuration(event.currentTarget.duration); event.currentTarget.playbackRate = rate; }} onTimeUpdate={(event) => { setCurrentTime(event.currentTarget.currentTime); if (previewEnd !== null && event.currentTarget.currentTime >= previewEnd - .04) { event.currentTarget.pause(); event.currentTarget.currentTime = previewEnd; setPreviewEnd(null); } }} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)}/> : <button onClick={() => fileRef.current?.click()} className="flex h-full w-full flex-col items-center justify-center p-8 text-center"><FileVideo size={50} className="text-cyan-300"/><h2 className="mt-4 font-bold text-white">Select the local match video</h2><p className="mt-2 max-w-md text-sm text-slate-500">The file is not uploaded. Only timestamps and action data are stored.</p></button>}</div><div className="border-t border-white/10 p-3"><input aria-label="Video position" type="range" min={0} max={duration || 0} step={.1} value={Math.min(currentTime, duration || 0)} disabled={!sourceUrl} onChange={(event) => seekTo(Number(event.target.value))} className="w-full accent-cyan-300"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Button size="icon" disabled={!sourceUrl} onClick={() => seekTo(currentTime - 5)}><ChevronLeft size={17}/></Button><Button size="icon" variant="primary" disabled={!sourceUrl} onClick={() => { const video = videoRef.current; if (video?.paused) void video.play(); else video?.pause(); }}>{playing ? <Pause size={17}/> : <Play size={17}/>}</Button><Button size="icon" disabled={!sourceUrl} onClick={() => seekTo(currentTime + 5)}><ChevronRight size={17}/></Button><div className="flex overflow-hidden rounded-lg border border-white/10">{[.5, 1, 2, 4].map((value) => <button key={value} onClick={() => { setRate(value); if (videoRef.current) videoRef.current.playbackRate = value; }} className={`h-9 px-2.5 text-xs ${rate === value ? "bg-cyan-300 text-slate-950" : "bg-white/[.04] text-slate-300"}`}>{value}×</button>)}</div></div><span className="inline-flex items-center gap-2 font-mono text-sm text-white"><Clock3 size={15} className="text-cyan-300"/>{formatTime(currentTime)} / {formatTime(duration)}</span></div></div></Panel><Timeline players={match.club.players} actions={filtered} duration={timelineDuration} onSelect={preview}/></div>
      <Panel className="max-h-[720px] overflow-hidden"><div className="border-b border-white/10 p-3"><div className="flex items-center justify-between"><div><Label>Recorded actions</Label><p className="mt-1 text-xs text-slate-500">{filtered.length} actions</p></div><select aria-label="Filter by player" value={filterPlayerId} onChange={(event) => setFilterPlayerId(event.target.value)} className="max-w-32 rounded-md border border-white/10 bg-pitch-900 p-1.5 text-xs"><option value="all">All</option>{match.club.players.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</select></div></div><div className="max-h-[650px] overflow-y-auto">{filtered.length === 0 ? <p className="p-4 text-sm text-slate-500">No actions have been recorded yet.</p> : filtered.map((action) => <div key={action.id} className="border-b border-white/[.06] p-3"><button onClick={() => preview(action)} className="flex w-full items-center gap-2 text-left"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: actionTypeByKey.get(action.actionKey)?.color }}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold text-white">{displayAction(action)}</span><span className="block truncate text-[11px] text-slate-500">{action.player.name}</span></span><span className="font-mono text-[10px] text-slate-500">{formatTime(action.eventTimeSeconds)}</span></button><div className="mt-2 flex items-center gap-2"><Badge className={action.outcome === "positive" ? "text-emerald-200" : action.outcome === "negative" ? "text-red-200" : ""}>{action.outcome === "positive" ? "Positive" : action.outcome === "negative" ? "Negative" : "Neutral"}</Badge><button aria-label="Edit action" onClick={() => setEditing(action)} className="ml-auto text-slate-500 hover:text-cyan-300"><Pencil size={14}/></button><button aria-label="Delete action" onClick={() => void removeAction(action)} className="text-slate-600 hover:text-red-300"><Trash2 size={14}/></button></div></div>)}</div></Panel>
    </div>
    {pending ? <ActionDialog matchId={matchId} pending={pending} duration={duration || match.video?.durationSeconds || 0} onClose={() => setPending(null)} onSaved={(action) => { setMatch((current) => current ? { ...current, playerActions: [...current.playerActions, action].sort((a, b) => a.eventTimeSeconds - b.eventTimeSeconds) } : current); setPending(null); setNotice(`${displayAction(action)} saved for ${action.player.name}.`); }}/>: null}
    {editing ? <ActionDialog matchId={matchId} pending={{ player: editing.player, eventTimeSeconds: editing.eventTimeSeconds }} duration={duration || match.video?.durationSeconds || 0} action={editing} onClose={() => setEditing(null)} onSaved={(saved) => { setMatch((current) => current ? { ...current, playerActions: current.playerActions.map((item) => item.id === saved.id ? saved : item) } : current); setEditing(null); setNotice("Action updated successfully."); }}/>: null}
  </div>;
}

function displayAction(action: Pick<ActionRecord, "actionKey" | "actionName">) { return actionTypeByKey.get(action.actionKey)?.name || action.actionName; }
function PlayerPhoto({ player }: { player: PlayerRecord }) { return <span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-cyan-300/10 text-cyan-200"><span className="h-full w-full bg-cover bg-center transition" style={player.photoUrl ? { backgroundImage: `url(${player.photoUrl})` } : undefined}>{!player.photoUrl ? <span className="flex h-full items-center justify-center"><UserRound size={22}/></span> : null}</span></span>; }
function Timeline({ players, actions, duration, onSelect }: { players: PlayerRecord[]; actions: ActionRecord[]; duration: number; onSelect: (action: ActionRecord) => void }) { const visible = players.filter((player) => actions.some((action) => action.playerId === player.id)); return <Panel className="p-4"><div className="flex items-center justify-between"><div><Label>Timeline</Label><h2 className="mt-1 font-bold text-white">Actions by player</h2></div><span className="text-xs text-slate-500">−4s / +6s</span></div><div className="mt-4 overflow-x-auto"><div className="min-w-[680px] overflow-hidden rounded-lg border border-white/10">{visible.length ? visible.map((player) => <div key={player.id} className="grid grid-cols-[10rem_minmax(0,1fr)] border-b border-white/[.07] last:border-0"><div className="truncate border-r border-white/[.07] px-3 py-2 text-xs text-slate-300">{player.name}</div><div className="relative min-h-10 bg-black/20">{actions.filter((action) => action.playerId === player.id).map((action) => { const left = Math.max(0, (action.startTimeSeconds / duration) * 100); const width = Math.max(.6, ((action.endTimeSeconds - action.startTimeSeconds) / duration) * 100); return <button key={action.id} title={`${displayAction(action)} · ${formatTime(action.eventTimeSeconds)}`} onClick={() => onSelect(action)} className="absolute top-1/2 h-4 -translate-y-1/2 rounded-full border border-white/25 hover:h-6" style={{ left: `${left}%`, width: `${width}%`, backgroundColor: actionTypeByKey.get(action.actionKey)?.color || "#22d3ee" }}/>; })}</div></div>) : <p className="p-4 text-sm text-slate-500">No actions yet.</p>}</div></div></Panel>; }

function ActionDialog({ matchId, pending, duration, action, onClose, onSaved }: { matchId: string; pending: PendingAction; duration: number; action?: ActionRecord; onClose: () => void; onSaved: (action: ActionRecord) => void }) {
  const types = actionsForPlayer(pending.player.isGoalkeeper); const groups = [...new Set(types.map((type) => type.group))]; const [selected, setSelected] = useState<ActionType | null>(() => action ? actionTypeByKey.get(action.actionKey) || null : null); const [coordinate, setCoordinate] = useState<Coordinate | null>(() => action?.fieldX != null && action.fieldY != null ? { x: action.fieldX, y: action.fieldY } : null); const [notes, setNotes] = useState(action?.notes || ""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function persist() { if (!selected) return setError("Select the action performed."); setSaving(true); setError(null); try { const payload = { actionKey: selected.key, fieldX: coordinate?.x ?? null, fieldY: coordinate?.y ?? null, notes, outcome: selected.outcome }; const saved = action ? await apiFetch<ActionRecord>(`/api/actions/${action.id}`, { method: "PATCH", body: JSON.stringify(payload) }) : await apiFetch<ActionRecord>(`/api/matches/${matchId}/actions`, { method: "POST", body: JSON.stringify({ ...payload, playerId: pending.player.id, eventTimeSeconds: pending.eventTimeSeconds }) }); onSaved(saved); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save the action."); setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-3 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><Panel className="max-h-[94vh] w-full max-w-5xl overflow-y-auto p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><PlayerPhoto player={pending.player}/><div><Label>{action ? "Edit action" : "Classify action"}</Label><h2 className="mt-1 text-xl font-bold text-white">{pending.player.name}</h2><p className="mt-1 text-xs text-slate-400">Event {formatTime(pending.eventTimeSeconds)} · clip {formatTime(Math.max(0, pending.eventTimeSeconds - 4))}–{formatTime(Math.min(duration || Infinity, pending.eventTimeSeconds + 6))}</p></div></div><Button size="icon" onClick={onClose}><X size={16}/></Button></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="space-y-4">{groups.map((group) => <div key={group}><Label>{group}</Label><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{types.filter((type) => type.group === group).map((type) => <button key={type.key} onClick={() => setSelected(type)} className={`min-h-12 rounded-lg border px-3 py-2 text-left text-xs font-semibold transition ${selected?.key === type.key ? "text-white ring-2 ring-white/20" : "border-white/10 bg-white/[.04] text-slate-300 hover:bg-white/[.09]"}`} style={selected?.key === type.key ? { borderColor: type.color, backgroundColor: `${type.color}25` } : undefined}>{type.name}</button>)}</div></div>)}</div><div><Label>Action location</Label><p className="mt-1 text-xs text-slate-500">Click the pitch to set the location used by the action map.</p><Pitch value={coordinate} onChange={setCoordinate} className="mt-3"/><div className="mt-4"><Label>Notes</Label><TextArea className="mt-1" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional note"/></div></div></div>{error ? <p className="mt-4 text-sm text-red-300">{error}</p> : null}<div className="mt-5 flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button variant="primary" disabled={saving || !selected} onClick={() => void persist()}>{saving ? "Saving…" : action ? "Save changes" : "Save action"}</Button></div></Panel></div>;
}
