"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, Clock3, FileVideo, Pause, Play, Trash2, Upload, UserRound, X } from "lucide-react";
import { actionTypeByKey, actionsForPlayer, type ActionType } from "@/lib/action-types";
import type { ActionRecord, MatchDetail, PlayerRecord } from "@/lib/domain";
import { apiFetch } from "@/lib/http";
import { getRememberedMatchVideo, rememberMatchVideo } from "@/lib/local-video-store";
import { formatTime, roundTime } from "@/lib/time";
import { Pitch, type Coordinate } from "@/components/pitch";
import { Badge, Button, Label, Panel, TextArea } from "@/components/ui";

type PendingAction = { player: PlayerRecord; eventTimeSeconds: number };
export function AnalysisWorkspace({ matchId }: { matchId: string }) {
  const videoRef = useRef<HTMLVideoElement | null>(null); const fileRef = useRef<HTMLInputElement | null>(null);
  const [match, setMatch] = useState<MatchDetail | null>(null); const [sourceUrl, setSourceUrl] = useState<string | null>(null); const [duration, setDuration] = useState(0); const [currentTime, setCurrentTime] = useState(0); const [playing, setPlaying] = useState(false); const [rate, setRate] = useState(1); const [pending, setPending] = useState<PendingAction | null>(null); const [filterPlayerId, setFilterPlayerId] = useState<string>("all"); const [previewEnd, setPreviewEnd] = useState<number | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { try { setMatch(await apiFetch<MatchDetail>(`/api/matches/${matchId}`)); } catch (e) { setNotice(e instanceof Error ? e.message : "Não foi possível carregar o jogo."); } }, [matchId]);
  useEffect(() => { void load(); getRememberedMatchVideo(matchId).then((file) => { if (file) setSourceUrl(URL.createObjectURL(file)); }).catch(() => undefined); }, [load, matchId]);
  useEffect(() => () => { if (sourceUrl) URL.revokeObjectURL(sourceUrl); }, [sourceUrl]);

  async function chooseVideo(file?: File) {
    if (!file) return; if (sourceUrl) URL.revokeObjectURL(sourceUrl);
    const url = URL.createObjectURL(file); setSourceUrl(url); await rememberMatchVideo(matchId, file).catch(() => undefined);
    const probe = document.createElement("video"); probe.preload = "metadata"; probe.src = url;
    await new Promise<void>((resolve, reject) => { probe.onloadedmetadata = () => resolve(); probe.onerror = () => reject(new Error("Não foi possível ler o vídeo.")); });
    await apiFetch(`/api/matches/${matchId}/video`, { method: "PUT", body: JSON.stringify({ fileName: file.name, fileSize: file.size, durationSeconds: probe.duration, mimeType: file.type || "video/mp4", lastModified: new Date(file.lastModified).toISOString() }) });
    setDuration(probe.duration); await load(); setNotice("Vídeo selecionado. O ficheiro permanece neste dispositivo.");
  }
  function seekTo(seconds: number) { const video = videoRef.current; if (!video) return; const next = Math.max(0, Math.min(duration || video.duration || 0, seconds)); video.currentTime = next; setCurrentTime(next); }
  function tagPlayer(player: PlayerRecord) { if (!sourceUrl) { setNotice("Seleciona primeiro o vídeo deste jogo."); return; } const video = videoRef.current; const eventTimeSeconds = roundTime(video?.currentTime ?? currentTime); video?.pause(); setPending({ player, eventTimeSeconds }); }
  function preview(action: ActionRecord) { const video = videoRef.current; if (!video) { setNotice("Seleciona novamente o vídeo para reproduzir o clip."); return; } setPreviewEnd(action.endTimeSeconds); video.currentTime = action.startTimeSeconds; void video.play(); }
  async function removeAction(action: ActionRecord) { if (!confirm(`Eliminar ${action.actionName} de ${action.player.name}?`)) return; await apiFetch(`/api/actions/${action.id}`, { method: "DELETE" }); setMatch((m) => m ? { ...m, playerActions: m.playerActions.filter((a) => a.id !== action.id) } : m); }
  if (!match) return <Panel className="p-8 text-center text-slate-400">{notice || "A carregar análise…"}</Panel>;
  const filtered = filterPlayerId === "all" ? match.playerActions : match.playerActions.filter((a) => a.playerId === filterPlayerId);
  const timelineDuration = duration || match.video?.durationSeconds || Math.max(1, ...match.playerActions.map((a) => a.endTimeSeconds));
  return <div className="analysis-layout space-y-4">
    <input ref={fileRef} type="file" accept="video/*" className="hidden" onChange={(e) => void chooseVideo(e.target.files?.[0])}/>
    <header className="flex flex-col justify-between gap-4 rounded-xl border border-white/10 bg-white/[.045] p-4 lg:flex-row lg:items-center"><div><Link href="/" className="inline-flex items-center gap-1 text-xs text-slate-500 hover:text-white"><ArrowLeft size={13}/>Jogos</Link><h1 className="mt-2 text-2xl font-bold text-white">{match.title}</h1><p className="mt-1 text-sm text-slate-500">{match.club.name} vs {match.opponentName} · {match.competition.name}</p></div><Button onClick={() => fileRef.current?.click()}><Upload size={16}/>{sourceUrl ? "Alterar vídeo" : "Selecionar vídeo"}</Button></header>
    {notice ? <div role="status" className="fixed bottom-4 right-4 z-50 flex max-w-sm gap-3 rounded-xl border border-cyan-300/25 bg-pitch-950/95 px-4 py-3 text-sm text-cyan-100 shadow-2xl"><span>{notice}</span><button onClick={() => setNotice(null)}><X size={15}/></button></div> : null}
    <div className="grid items-start gap-4 xl:grid-cols-[17rem_minmax(0,1fr)_21rem]">
      <Panel className="max-h-[720px] overflow-hidden"><div className="border-b border-white/10 p-3"><Label>Plantel</Label><p className="mt-1 text-xs text-slate-500">Clica no jogador no instante da ação</p></div><div className="grid max-h-[650px] grid-cols-2 gap-2 overflow-y-auto p-2 xl:grid-cols-1">{match.club.players.map((player) => <button key={player.id} onClick={() => tagPlayer(player)} className="player-card flex min-w-0 items-center gap-3 rounded-lg border border-white/10 bg-white/[.035] p-2 text-left transition hover:border-cyan-300/40 hover:bg-cyan-300/10"><PlayerPhoto player={player}/><span className="min-w-0"><span className="block truncate text-sm font-bold text-white">{player.shirtNumber ? `${player.shirtNumber} · ` : ""}{player.name}</span><span className="block truncate text-[11px] text-slate-500">{player.position || "Sem posição"}</span></span></button>)}</div></Panel>
      <div className="space-y-4"><Panel className="overflow-hidden"><div className="relative aspect-video bg-black">{sourceUrl ? <video ref={videoRef} src={sourceUrl} className="h-full w-full" playsInline onLoadedMetadata={(e) => { setDuration(e.currentTarget.duration); e.currentTarget.playbackRate = rate; }} onTimeUpdate={(e) => { setCurrentTime(e.currentTarget.currentTime); if (previewEnd !== null && e.currentTarget.currentTime >= previewEnd - .04) { e.currentTarget.pause(); e.currentTarget.currentTime = previewEnd; setPreviewEnd(null); } }} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)}/> : <button onClick={() => fileRef.current?.click()} className="flex h-full w-full flex-col items-center justify-center p-8 text-center"><FileVideo size={50} className="text-cyan-300"/><h2 className="mt-4 font-bold text-white">Seleciona o vídeo local do jogo</h2><p className="mt-2 max-w-md text-sm text-slate-500">O ficheiro não é enviado. Guardamos apenas os timestamps e os dados das ações.</p></button>}</div><div className="border-t border-white/10 p-3"><input aria-label="Posição do vídeo" type="range" min={0} max={duration || 0} step={.1} value={Math.min(currentTime, duration || 0)} disabled={!sourceUrl} onChange={(e) => seekTo(Number(e.target.value))} className="w-full accent-cyan-300"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Button size="icon" disabled={!sourceUrl} onClick={() => seekTo(currentTime - 5)}><ChevronLeft size={17}/></Button><Button size="icon" variant="primary" disabled={!sourceUrl} onClick={() => { const video = videoRef.current; if (video?.paused) void video.play(); else video?.pause(); }}>{playing ? <Pause size={17}/> : <Play size={17}/>}</Button><Button size="icon" disabled={!sourceUrl} onClick={() => seekTo(currentTime + 5)}><ChevronRight size={17}/></Button><div className="flex overflow-hidden rounded-lg border border-white/10">{[.5, 1, 2, 4].map((value) => <button key={value} onClick={() => { setRate(value); if (videoRef.current) videoRef.current.playbackRate = value; }} className={`h-9 px-2.5 text-xs ${rate === value ? "bg-cyan-300 text-slate-950" : "bg-white/[.04] text-slate-300"}`}>{value}×</button>)}</div></div><span className="inline-flex items-center gap-2 font-mono text-sm text-white"><Clock3 size={15} className="text-cyan-300"/>{formatTime(currentTime)} / {formatTime(duration)}</span></div></div></Panel>
        <Timeline actions={filtered} duration={timelineDuration} onSelect={preview}/>
      </div>
      <Panel className="max-h-[720px] overflow-hidden"><div className="border-b border-white/10 p-3"><div className="flex items-center justify-between"><div><Label>Ações registadas</Label><p className="mt-1 text-xs text-slate-500">{filtered.length} ações</p></div><select aria-label="Filtrar jogador" value={filterPlayerId} onChange={(e) => setFilterPlayerId(e.target.value)} className="max-w-32 rounded-md border border-white/10 bg-pitch-900 p-1.5 text-xs"><option value="all">Todos</option>{match.club.players.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div><div className="max-h-[650px] overflow-y-auto">{filtered.length === 0 ? <p className="p-4 text-sm text-slate-500">Ainda não existem ações.</p> : filtered.map((action) => <div key={action.id} className="border-b border-white/[.06] p-3"><button onClick={() => preview(action)} className="flex w-full items-center gap-2 text-left"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: actionTypeByKey.get(action.actionKey)?.color }}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold text-white">{action.actionName}</span><span className="block truncate text-[11px] text-slate-500">{action.player.name}</span></span><span className="font-mono text-[10px] text-slate-500">{formatTime(action.eventTimeSeconds)}</span></button><div className="mt-2 flex items-center justify-between"><Badge className={action.outcome === "positive" ? "text-emerald-200" : action.outcome === "negative" ? "text-red-200" : ""}>{action.outcome === "positive" ? "Positiva" : action.outcome === "negative" ? "Negativa" : "Neutra"}</Badge><button aria-label="Eliminar ação" onClick={() => void removeAction(action)} className="text-slate-600 hover:text-red-300"><Trash2 size={14}/></button></div></div>)}</div></Panel>
    </div>
    {pending ? <ActionDialog matchId={matchId} pending={pending} duration={duration || match.video?.durationSeconds || 0} onClose={() => setPending(null)} onSaved={(action) => { setMatch((m) => m ? { ...m, playerActions: [...m.playerActions, action].sort((a, b) => a.eventTimeSeconds - b.eventTimeSeconds) } : m); setPending(null); setNotice(`${action.actionName} guardada para ${action.player.name}.`); }}/>: null}
  </div>;
}

function PlayerPhoto({ player }: { player: PlayerRecord }) { return <span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-cyan-300/10 text-cyan-200"><span className="h-full w-full bg-cover bg-center transition" style={player.photoUrl ? { backgroundImage: `url(${player.photoUrl})` } : undefined}>{!player.photoUrl ? <span className="flex h-full items-center justify-center"><UserRound size={22}/></span> : null}</span></span>; }
function Timeline({ actions, duration, onSelect }: { actions: ActionRecord[]; duration: number; onSelect: (action: ActionRecord) => void }) { return <Panel className="p-4"><div className="flex items-center justify-between"><div><Label>Timeline</Label><h2 className="mt-1 font-bold text-white">Ações no vídeo</h2></div><span className="text-xs text-slate-500">−4s / +6s</span></div><div className="relative mt-4 h-12 overflow-hidden rounded-lg border border-white/10 bg-black/20">{actions.map((action) => { const left = (action.startTimeSeconds / duration) * 100; const width = Math.max(.6, ((action.endTimeSeconds - action.startTimeSeconds) / duration) * 100); return <button key={action.id} title={`${action.player.name} · ${action.actionName}`} onClick={() => onSelect(action)} className="absolute top-1/2 h-5 -translate-y-1/2 rounded-full border border-white/25 hover:h-7" style={{ left: `${left}%`, width: `${width}%`, backgroundColor: actionTypeByKey.get(action.actionKey)?.color || "#22d3ee" }}/>; })}</div></Panel>; }

function ActionDialog({ matchId, pending, duration, onClose, onSaved }: { matchId: string; pending: PendingAction; duration: number; onClose: () => void; onSaved: (action: ActionRecord) => void }) {
  const types = actionsForPlayer(pending.player.isGoalkeeper); const groups = [...new Set(types.map((type) => type.group))]; const [selected, setSelected] = useState<ActionType | null>(null); const [coordinate, setCoordinate] = useState<Coordinate | null>(null); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  async function persist() { if (!selected) { setError("Seleciona a ação realizada."); return; } setSaving(true); setError(null); try { const action = await apiFetch<ActionRecord>(`/api/matches/${matchId}/actions`, { method: "POST", body: JSON.stringify({ playerId: pending.player.id, actionKey: selected.key, eventTimeSeconds: pending.eventTimeSeconds, fieldX: coordinate?.x, fieldY: coordinate?.y, notes }) }); onSaved(action); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível guardar a ação."); setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-3 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><Panel className="max-h-[94vh] w-full max-w-5xl overflow-y-auto p-5"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><PlayerPhoto player={pending.player}/><div><Label>Classificar ação</Label><h2 className="mt-1 text-xl font-bold text-white">{pending.player.name}</h2><p className="mt-1 text-xs text-slate-400">Instante {formatTime(pending.eventTimeSeconds)} · clip {formatTime(Math.max(0, pending.eventTimeSeconds - 4))}–{formatTime(Math.min(duration || Infinity, pending.eventTimeSeconds + 6))}</p></div></div><Button size="icon" onClick={onClose}><X size={16}/></Button></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"> <div className="space-y-4">{groups.map((group) => <div key={group}><Label>{group}</Label><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{types.filter((type) => type.group === group).map((type) => <button key={type.key} onClick={() => setSelected(type)} className={`min-h-12 rounded-lg border px-3 py-2 text-left text-xs font-semibold transition ${selected?.key === type.key ? "text-white ring-2 ring-white/20" : "border-white/10 bg-white/[.04] text-slate-300 hover:bg-white/[.09]"}`} style={selected?.key === type.key ? { borderColor: type.color, backgroundColor: `${type.color}25` } : undefined}>{type.name}</button>)}</div></div>)}</div><div><Label>Local da ação no campo</Label><p className="mt-1 text-xs text-slate-500">Clica no campo para posicionar a ação e alimentar o heatmap.</p><Pitch value={coordinate} onChange={setCoordinate} className="mt-3"/><div className="mt-4"><Label>Notas</Label><TextArea className="mt-1" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Observação opcional"/></div></div></div>{error ? <p className="mt-4 text-sm text-red-300">{error}</p> : null}<div className="mt-5 flex justify-end gap-2"><Button onClick={onClose}>Cancelar</Button><Button variant="primary" disabled={saving || !selected} onClick={() => void persist()}>{saving ? "A guardar…" : "Guardar ação"}</Button></div></Panel></div>;
}
