"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, MapPinned } from "lucide-react";
import { jsPDF } from "jspdf";
import { actionTypeByKey, allActionTypes } from "@/lib/action-types";
import { apiFetch } from "@/lib/http";
import { formatTime } from "@/lib/time";
import { ActionClipPlayer, type ClipAction } from "@/components/action-clip-player";
import { Pitch } from "@/components/pitch";
import { Badge, Button, Label, Panel, Select } from "@/components/ui";

type Player = { id: string; name: string; club: { name: string } };
type Match = { id: string; roundName: string | null; club: { name: string }; opponentClub: { name: string }; competition: { id: string; name: string; season: { name: string } }; video: { fileName: string } | null };
type MapAction = ClipAction & { playerId: string; actionKey: string; outcome: string | null; fieldX: number | null; fieldY: number | null; matchId: string; match: Match };
type Competition = { id: string; name: string; season: { name: string } };
export function MapsClient() {
  const [data, setData] = useState<{ players: Player[]; actions: MapAction[]; matches: Match[]; competitions: Competition[] }>({ players: [], actions: [], matches: [], competitions: [] }); const [playerId, setPlayerId] = useState("all"); const [actionKey, setActionKey] = useState("all"); const [competitionId, setCompetitionId] = useState("all"); const [matchId, setMatchId] = useState("all"); const [selectedId, setSelectedId] = useState<string | null>(null);
  useEffect(() => { apiFetch<typeof data>("/api/analytics").then(setData).catch(() => undefined); }, []);
  const availableMatches = useMemo(() => data.matches.filter((match) => competitionId === "all" || match.competition.id === competitionId), [competitionId, data.matches]);
  useEffect(() => { if (matchId !== "all" && !availableMatches.some((match) => match.id === matchId)) setMatchId("all"); }, [availableMatches, matchId]);
  const actions = useMemo(() => data.actions.filter((action) => action.fieldX != null && action.fieldY != null && (playerId === "all" || action.playerId === playerId) && (actionKey === "all" || action.actionKey === actionKey) && (competitionId === "all" || action.match.competition.id === competitionId) && (matchId === "all" || action.matchId === matchId)), [data.actions, playerId, actionKey, competitionId, matchId]);
  useEffect(() => { if (selectedId && !actions.some((action) => action.id === selectedId)) setSelectedId(null); }, [actions, selectedId]);
  const selected = actions.find((action) => action.id === selectedId) || null; const points = actions.map((action) => ({ id: action.id, x: action.fieldX!, y: action.fieldY!, color: outcomeColor(action.outcome), active: action.id === selectedId, label: `${action.player.name} · ${actionTypeByKey.get(action.actionKey)?.name || action.actionName}`, details: [`Time: ${formatTime(action.eventTimeSeconds)}`, `Match: ${action.match.club.name} vs ${action.match.opponentClub.name}`, `${action.match.competition.season.name} · ${action.match.competition.name}`] })); const legend = [...new Set(actions.map((action) => action.actionKey))].map((key) => ({ key, count: actions.filter((action) => action.actionKey === key).length }));
  async function exportPdf() { const document = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" }); const player = data.players.find((item) => item.id === playerId)?.name || "All players"; const match = data.matches.find((item) => item.id === matchId); const competition = data.competitions.find((item) => item.id === competitionId); const action = actionTypeByKey.get(actionKey)?.name || "All actions"; document.setFillColor(6, 17, 17); document.rect(0, 0, 297, 210, "F"); document.setTextColor(255, 255, 255); document.setFontSize(20); document.text("Player Action Map", 15, 18); document.setFontSize(10); document.setTextColor(170, 200, 200); document.text(`Player: ${player}`, 15, 28); document.text(`Match: ${match ? `${match.club.name} vs ${match.opponentClub.name}` : "All matches"}`, 15, 34); document.text(`Competition: ${competition ? `${competition.season.name} · ${competition.name}` : "All competitions"}`, 15, 40); document.text(`Action: ${action}`, 15, 46); const positive = actions.filter((item) => item.outcome === "positive").length; const negative = actions.filter((item) => item.outcome === "negative").length; const neutral = actions.length - positive - negative; document.setTextColor(52, 211, 153); document.text(`Positive: ${positive}`, 220, 28); document.setTextColor(251, 113, 133); document.text(`Negative: ${negative}`, 220, 34); drawPdfPitch(document, 15, 55, 267, 100, actions); document.setTextColor(255, 255, 255); document.setFontSize(11); document.text("Outcome legend", 15, 165); document.setFontSize(9); drawPdfLegendItem(document, 15, 173, "#34d399", `Positive: ${positive}`); drawPdfLegendItem(document, 58, 173, "#fb7185", `Negative: ${negative}`); drawPdfLegendItem(document, 104, 173, "#fbbf24", `Neutral: ${neutral}`); document.setTextColor(255, 255, 255); document.setFontSize(11); document.text("Action totals", 15, 184); document.setFontSize(9); let x = 15; let y = 192; for (const item of legend) { const label = `${actionTypeByKey.get(item.key)?.name || item.key}: ${item.count}`; const width = document.getTextWidth(label) + 10; if (x + width > 282) { x = 15; y += 8; } if (y > 202) { document.addPage(); document.setFillColor(6, 17, 17); document.rect(0, 0, 297, 210, "F"); document.setTextColor(255, 255, 255); document.setFontSize(14); document.text("Action totals (continued)", 15, 15); document.setFontSize(9); x = 15; y = 25; } drawPdfLegendItem(document, x, y, actionTypeByKey.get(item.key)?.color || "#22d3ee", label); x += width; } document.save(`player-action-map-${player.replace(/\s+/g, "-").toLowerCase()}.pdf`); }
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><Label>Spatial analysis</Label><h1 className="mt-2 text-3xl font-bold text-white">Action maps</h1><p className="mt-2 text-sm text-slate-400">Hover over a point for player, action, time and match. Click it to play the clip.</p></div><Button variant="primary" disabled={!actions.length} onClick={() => void exportPdf()}><Download size={16}/>Export map PDF</Button></div>
    <Panel className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><Filter label="Player" value={playerId} onChange={setPlayerId}><option value="all">All players</option>{data.players.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</Filter><Filter label="Action" value={actionKey} onChange={setActionKey}><option value="all">All actions</option>{allActionTypes.map((action) => <option key={action.key} value={action.key}>{action.name}</option>)}</Filter><Filter label="Competition" value={competitionId} onChange={setCompetitionId}><option value="all">All competitions</option>{data.competitions.map((competition) => <option key={competition.id} value={competition.id}>{competition.season.name} · {competition.name}</option>)}</Filter><Filter label="Match" value={matchId} onChange={setMatchId}><option value="all">All matches</option>{availableMatches.map((match) => <option key={match.id} value={match.id}>{match.club.name} vs {match.opponentClub.name}</option>)}</Filter></Panel>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(20rem,.65fr)]"><Panel className="p-4"><div className="flex items-center justify-between"><div><Label>Pitch</Label><p className="mt-1 text-xs text-slate-500">{actions.length} located actions · green positive · red negative</p></div><MapPinned className="text-cyan-300"/></div><Pitch className="mt-4" points={points} onPointSelect={setSelectedId}/></Panel><ActionClipPlayer action={selected}/></div>
    <Panel className="p-4"><div className="flex items-center justify-between"><Label>Legend</Label><Badge>{actions.length} occurrences</Badge></div><div className="mt-3 flex flex-wrap gap-2"><LegendItem color="#34d399" label="Positive" count={actions.filter((action) => action.outcome === "positive").length}/><LegendItem color="#fb7185" label="Negative" count={actions.filter((action) => action.outcome === "negative").length}/><LegendItem color="#fbbf24" label="Neutral" count={actions.filter((action) => !action.outcome || action.outcome === "neutral").length}/></div><Label className="mt-5 block">Action totals</Label><div className="mt-2 flex flex-wrap gap-2">{legend.map(({ key, count }) => <span key={key} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300">{actionTypeByKey.get(key)?.name}<strong className="text-white">{count}</strong></span>)}</div></Panel>
  </div>;
}
function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label><Label>{label}</Label><Select className="mt-1" value={value} onChange={(event) => onChange(event.target.value)}>{children}</Select></label>; }
function LegendItem({ color, label, count }: { color: string; label: string; count: number }) { return <span className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300"><span className="h-3 w-3 rounded-full" style={{ backgroundColor: color }}/>{label}<strong className="text-white">{count}</strong></span>; }
function outcomeColor(outcome: string | null) { return outcome === "positive" ? "#34d399" : outcome === "negative" ? "#fb7185" : "#fbbf24"; }
function hexToRgb(hex: string): [number, number, number] { const value = hex.replace("#", ""); return [parseInt(value.slice(0, 2), 16), parseInt(value.slice(2, 4), 16), parseInt(value.slice(4, 6), 16)]; }
function drawPdfLegendItem(document: jsPDF, x: number, y: number, color: string, label: string) { document.setFillColor(...hexToRgb(color)); document.circle(x + 2, y - 1, 1.5, "F"); document.setTextColor(220, 235, 235); document.text(label, x + 6, y); }
function drawPdfPitch(document: jsPDF, x: number, y: number, width: number, height: number, actions: MapAction[]) { document.setFillColor(22, 118, 65); document.roundedRect(x, y, width, height, 2, 2, "F"); document.setDrawColor(255, 255, 255); document.setLineWidth(.4); document.rect(x + 2, y + 2, width - 4, height - 4); document.line(x + width / 2, y + 2, x + width / 2, y + height - 2); document.circle(x + width / 2, y + height / 2, height * .14); document.rect(x + 2, y + height * .2, width * .16, height * .6); document.rect(x + width * .84 - 2, y + height * .2, width * .16, height * .6); for (const action of actions) { const [r, g, b] = hexToRgb(outcomeColor(action.outcome)); document.setFillColor(r, g, b); document.setDrawColor(255, 255, 255); document.circle(x + (action.fieldX! / 100) * width, y + (action.fieldY! / 100) * height, 2, "FD"); } }
