"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, MapPinned } from "lucide-react";
import { jsPDF } from "jspdf";
import { actionTypeByKey, allActionTypes } from "@/lib/action-types";
import { apiFetch } from "@/lib/http";
import { formatTime } from "@/lib/time";
import { normalizeFieldPoint } from "@/lib/field-normalization";
import { ActionClipPlayer, type ClipAction } from "@/components/action-clip-player";
import { Pitch } from "@/components/pitch";
import { Badge, Button, Label, Panel, Select } from "@/components/ui";

type Player = { id: string; name: string; club: { name: string } };
type Match = { id: string; roundName: string | null; firstHalfAttacksRight: boolean; club: { name: string }; opponentClub: { name: string }; competition: { id: string; name: string; season: { name: string } }; video: { fileName: string } | null };
type MapAction = ClipAction & { playerId: string; actionKey: string; outcome: string | null; fieldX: number | null; fieldY: number | null; period: number | null; matchId: string; match: Match };
type Competition = { id: string; name: string; season: { name: string } };
export function MapsClient() {
  const [data, setData] = useState<{ players: Player[]; actions: MapAction[]; matches: Match[]; competitions: Competition[] }>({ players: [], actions: [], matches: [], competitions: [] }); const [playerId, setPlayerId] = useState("all"); const [actionKey, setActionKey] = useState("all"); const [competitionId, setCompetitionId] = useState("all"); const [matchIds, setMatchIds] = useState<string[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null);
  useEffect(() => { apiFetch<typeof data>("/api/analytics").then(setData).catch(() => undefined); }, []);
  const availableMatches = useMemo(() => data.matches.filter((match) => competitionId === "all" || match.competition.id === competitionId), [competitionId, data.matches]);
  useEffect(() => { setMatchIds((current) => { const next = current.filter((id) => availableMatches.some((match) => match.id === id)); return next.length === current.length ? current : next; }); }, [availableMatches]);
  const locatedActions = useMemo(() => data.actions.filter((action) => action.fieldX != null && action.fieldY != null && (playerId === "all" || action.playerId === playerId) && (actionKey === "all" || action.actionKey === actionKey) && (competitionId === "all" || action.match.competition.id === competitionId) && (!matchIds.length || matchIds.includes(action.matchId))), [data.actions, playerId, actionKey, competitionId, matchIds]);
  const actions = useMemo(() => locatedActions.filter((action) => action.period !== null), [locatedActions]);
  const unassignedCount = locatedActions.length - actions.length;
  useEffect(() => { if (selectedId && !actions.some((action) => action.id === selectedId)) setSelectedId(null); }, [actions, selectedId]);
  const normalizedActions = actions.map((action) => { const point = normalizeFieldPoint({ x: action.fieldX!, y: action.fieldY! }, action.period, action.match.firstHalfAttacksRight); return { ...action, fieldX: point.x, fieldY: point.y }; });
  const selected = actions.find((action) => action.id === selectedId) || null; const points = normalizedActions.map((action) => ({ id: action.id, x: action.fieldX!, y: action.fieldY!, color: outcomeColor(action.outcome), active: action.id === selectedId, label: `${action.player.name} · ${actionTypeByKey.get(action.actionKey)?.name || action.actionName}`, details: [`Time: ${formatTime(action.eventTimeSeconds)} · ${action.period === 1 ? "1st half" : "2nd half"}`, `Match: ${action.match.club.name} vs ${action.match.opponentClub.name}`, `${action.match.competition.season.name} · ${action.match.competition.name}`, "Normalized to left-to-right attack"] })); const legend = [...new Set(actions.map((action) => action.actionKey))].map((key) => ({ key, count: actions.filter((action) => action.actionKey === key).length }));
  async function exportPdf() { const document = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" }); const player = data.players.find((item) => item.id === playerId)?.name || "All players"; const selectedMatches = data.matches.filter((item) => matchIds.includes(item.id)); const matchLabel = !matchIds.length ? "All matches" : selectedMatches.length === 1 ? `${selectedMatches[0].club.name} vs ${selectedMatches[0].opponentClub.name}` : `${selectedMatches.length} selected matches`; const competition = data.competitions.find((item) => item.id === competitionId); const action = actionTypeByKey.get(actionKey)?.name || "All actions"; document.setFillColor(6, 17, 17); document.rect(0, 0, 297, 210, "F"); document.setTextColor(255, 255, 255); document.setFontSize(20); document.text("Player Action Map", 15, 18); document.setFontSize(10); document.setTextColor(170, 200, 200); document.text(`Player: ${player}`, 15, 28); document.text(`Matches: ${matchLabel}`, 15, 34); document.text(`Competition: ${competition ? `${competition.season.name} · ${competition.name}` : "All competitions"}`, 15, 40); document.text(`Action: ${action} · normalized left-to-right`, 15, 46); const positive = actions.filter((item) => item.outcome === "positive").length; const negative = actions.filter((item) => item.outcome === "negative").length; const neutral = actions.length - positive - negative; document.setTextColor(52, 211, 153); document.text(`Positive: ${positive}`, 220, 28); document.setTextColor(251, 113, 133); document.text(`Negative: ${negative}`, 220, 34); drawPdfPitch(document, 15, 55, 267, 100, normalizedActions); document.setTextColor(255, 255, 255); document.setFontSize(11); document.text("Outcome legend", 15, 165); document.setFontSize(9); drawPdfLegendItem(document, 15, 173, "#34d399", `Positive: ${positive}`); drawPdfLegendItem(document, 58, 173, "#fb7185", `Negative: ${negative}`); drawPdfLegendItem(document, 104, 173, "#fbbf24", `Neutral: ${neutral}`); document.setTextColor(255, 255, 255); document.setFontSize(11); document.text("Action totals", 15, 184); document.setFontSize(9); let x = 15; let y = 192; for (const item of legend) { const label = `${actionTypeByKey.get(item.key)?.name || item.key}: ${item.count}`; const width = document.getTextWidth(label) + 10; if (x + width > 282) { x = 15; y += 8; } if (y > 202) { document.addPage(); document.setFillColor(6, 17, 17); document.rect(0, 0, 297, 210, "F"); document.setTextColor(255, 255, 255); document.setFontSize(14); document.text("Action totals (continued)", 15, 15); document.setFontSize(9); x = 15; y = 25; } drawPdfLegendItem(document, x, y, actionTypeByKey.get(item.key)?.color || "#22d3ee", label); x += width; } document.save(`player-action-map-${player.replace(/\s+/g, "-").toLowerCase()}.pdf`); }
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><Label>Spatial analysis</Label><h1 className="mt-2 text-3xl font-bold text-white">Action maps</h1><p className="mt-2 text-sm text-slate-400">Hover over a point for player, action, time and match. Click it to play the clip.</p></div><Button variant="primary" disabled={!actions.length} onClick={() => void exportPdf()}><Download size={16}/>Export map PDF</Button></div>
    <Panel className="relative z-40 grid overflow-visible gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><Filter label="Player" value={playerId} onChange={setPlayerId}><option value="all">All players</option>{data.players.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</Filter><Filter label="Action" value={actionKey} onChange={setActionKey}><option value="all">All actions</option>{allActionTypes.map((action) => <option key={action.key} value={action.key}>{action.name}</option>)}</Filter><Filter label="Competition" value={competitionId} onChange={setCompetitionId}><option value="all">All competitions</option>{data.competitions.map((competition) => <option key={competition.id} value={competition.id}>{competition.season.name} · {competition.name}</option>)}</Filter><MatchMultiSelect matches={availableMatches} value={matchIds} onChange={setMatchIds}/></Panel>
    {unassignedCount ? <div className="rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100">{unassignedCount} located {unassignedCount === 1 ? "action is" : "actions are"} waiting for the match period markers and will appear automatically afterwards.</div> : null}
    <div className="relative z-0 grid items-start gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(20rem,.65fr)]"><Panel className="p-4"><div className="flex items-center justify-between"><div><Label>Pitch</Label><p className="mt-1 text-xs text-slate-500">{actions.length} located actions · green positive · red negative</p></div><MapPinned className="text-cyan-300"/></div><Pitch className="mt-4" points={points} onPointSelect={setSelectedId}/></Panel><ActionClipPlayer action={selected}/></div>
    <Panel className="p-4"><div className="flex items-center justify-between"><Label>Legend</Label><Badge>{actions.length} occurrences</Badge></div><div className="mt-3 flex flex-wrap gap-2"><LegendItem color="#34d399" label="Positive" count={actions.filter((action) => action.outcome === "positive").length}/><LegendItem color="#fb7185" label="Negative" count={actions.filter((action) => action.outcome === "negative").length}/><LegendItem color="#fbbf24" label="Neutral" count={actions.filter((action) => !action.outcome || action.outcome === "neutral").length}/></div><Label className="mt-5 block">Action totals</Label><div className="mt-2 flex flex-wrap gap-2">{legend.map(({ key, count }) => <span key={key} className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300">{actionTypeByKey.get(key)?.name}<strong className="text-white">{count}</strong></span>)}</div></Panel>
  </div>;
}
function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label><Label>{label}</Label><Select className="mt-1" value={value} onChange={(event) => onChange(event.target.value)}>{children}</Select></label>; }
function MatchMultiSelect({ matches, value, onChange }: { matches: Match[]; value: string[]; onChange: (value: string[]) => void }) {
  const selected = new Set(value);
  const label = value.length === 0 ? "All matches" : value.length === 1 ? "1 match selected" : `${value.length} matches selected`;
  function toggle(id: string) { onChange(selected.has(id) ? value.filter((item) => item !== id) : [...value, id]); }
  return <div className="relative z-50 min-w-0"><Label>Matches</Label><details className="group relative mt-1"><summary className="flex h-10 cursor-pointer list-none items-center justify-between rounded-md border border-white/10 bg-pitch-950 px-3 text-sm text-slate-200 transition hover:border-cyan-300/35 [&::-webkit-details-marker]:hidden"><span className="truncate">{label}</span><span className="ml-2 text-[10px] text-slate-500 group-open:text-cyan-300">{value.length || "ALL"} ▾</span></summary><div className="absolute right-0 z-[60] mt-1 w-full min-w-72 overflow-hidden rounded-lg border border-white/10 bg-pitch-950 shadow-2xl"><button type="button" onClick={() => onChange([])} className={`flex w-full items-center gap-2 border-b border-white/10 px-3 py-2 text-left text-xs ${value.length === 0 ? "bg-cyan-300/10 text-cyan-100" : "text-slate-300 hover:bg-white/[.06]"}`}><span className={`flex h-4 w-4 items-center justify-center rounded border ${value.length === 0 ? "border-cyan-300 bg-cyan-300 text-slate-950" : "border-white/20"}`}>{value.length === 0 ? "✓" : ""}</span>All matches</button><div className="max-h-64 overflow-y-auto">{matches.length ? matches.map((match) => { const checked = selected.has(match.id); return <button key={match.id} type="button" onClick={() => toggle(match.id)} className={`flex w-full items-start gap-2 border-b border-white/[.05] px-3 py-2 text-left last:border-0 ${checked ? "bg-cyan-300/10" : "hover:bg-white/[.05]"}`}><span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border text-[10px] ${checked ? "border-cyan-300 bg-cyan-300 text-slate-950" : "border-white/20"}`}>{checked ? "✓" : ""}</span><span className="min-w-0"><span className="block truncate text-xs font-semibold text-white">{match.club.name} vs {match.opponentClub.name}</span><span className="block truncate text-[10px] text-slate-500">{match.competition.season.name} · {match.competition.name}{match.roundName ? ` · ${match.roundName}` : ""}</span></span></button>; }) : <p className="p-3 text-xs text-slate-500">No matches available for this competition.</p>}</div></div></details>{value.length ? <div className="mt-1.5 flex flex-wrap gap-1">{value.map((id) => { const match = matches.find((item) => item.id === id); return match ? <button key={id} type="button" title="Remove match" onClick={() => toggle(id)} className="max-w-full truncate rounded bg-cyan-300/10 px-2 py-1 text-[9px] text-cyan-100 hover:bg-red-300/10 hover:text-red-200">{match.opponentClub.name} ×</button> : null; })}<button type="button" onClick={() => onChange([])} className="px-1 text-[9px] text-slate-500 hover:text-white">Use all</button></div> : null}</div>;
}
function LegendItem({ color, label, count }: { color: string; label: string; count: number }) { return <span className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300"><span className="h-3 w-3 rounded-full" style={{ backgroundColor: color }}/>{label}<strong className="text-white">{count}</strong></span>; }
function outcomeColor(outcome: string | null) { return outcome === "positive" ? "#34d399" : outcome === "negative" ? "#fb7185" : "#fbbf24"; }
function hexToRgb(hex: string): [number, number, number] { const value = hex.replace("#", ""); return [parseInt(value.slice(0, 2), 16), parseInt(value.slice(2, 4), 16), parseInt(value.slice(4, 6), 16)]; }
function drawPdfLegendItem(document: jsPDF, x: number, y: number, color: string, label: string) { document.setFillColor(...hexToRgb(color)); document.circle(x + 2, y - 1, 1.5, "F"); document.setTextColor(220, 235, 235); document.text(label, x + 6, y); }
function drawPdfPitch(document: jsPDF, x: number, y: number, width: number, height: number, actions: MapAction[]) { document.setFillColor(22, 118, 65); document.roundedRect(x, y, width, height, 2, 2, "F"); document.setDrawColor(255, 255, 255); document.setLineWidth(.4); document.rect(x + 2, y + 2, width - 4, height - 4); document.line(x + width / 2, y + 2, x + width / 2, y + height - 2); document.circle(x + width / 2, y + height / 2, height * .14); document.rect(x + 2, y + height * .2, width * .16, height * .6); document.rect(x + width * .84 - 2, y + height * .2, width * .16, height * .6); for (const action of actions) { const [r, g, b] = hexToRgb(outcomeColor(action.outcome)); document.setFillColor(r, g, b); document.setDrawColor(255, 255, 255); document.circle(x + (action.fieldX! / 100) * width, y + (action.fieldY! / 100) * height, 2, "FD"); } }
