"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, ListVideo, MapPinned, Play } from "lucide-react";
import { jsPDF } from "jspdf";
import { actionFilterGroups, actionFilterName, actionMatchesFilter, actionTypeByKey, standaloneActionTypes } from "@/lib/action-types";
import { apiFetch } from "@/lib/http";
import { formatTime } from "@/lib/time";
import { normalizeFieldPoint } from "@/lib/field-normalization";
import { ActionClipPlayer, type ClipAction } from "@/components/action-clip-player";
import { Pitch } from "@/components/pitch";
import { Badge, Button, Label, Panel, Select } from "@/components/ui";

type Player = { id: string; name: string; club: { name: string } };
type Match = {
  id: string; roundName: string | null; firstHalfAttacksRight: boolean;
  firstHalfStartSeconds: number | null; firstHalfEndSeconds: number | null;
  secondHalfStartSeconds: number | null; secondHalfEndSeconds: number | null;
  club: { name: string }; opponentClub: { name: string };
  competition: { id: string; name: string; season: { name: string } };
  video: { fileName: string; storageStatus: "LOCAL" | "UPLOADING" | "READY" | "FAILED" } | null;
};
type SubactionSummary = { id: string; actionKey: string; actionName: string; outcome: string | null; fieldX: number | null; fieldY: number | null };
type MapMoment = ClipAction & { playerId: string; actionKey: string; outcome: string | null; fieldX: number | null; fieldY: number | null; period: number | null; matchId: string; match: Match; subActions: SubactionSummary[] };
type MapAction = ClipAction & { playerId: string; actionKey: string; outcome: string | null; fieldX: number | null; fieldY: number | null; period: number | null; matchId: string; parentActionId: string; sourceType: "subaction" | "occurrence"; match: Match };
type Competition = { id: string; name: string; season: { name: string } };
type OutcomeFilter = "positive" | "negative" | "neutral";
type HalfFilter = "all" | "1" | "2";
type MapMode = "original" | "normalized";
type Playlist = "moments" | `outcome:${OutcomeFilter}` | `action:${string}`;
type AnalyticsData = { players: Player[]; occurrences: MapMoment[]; actions: MapAction[]; matches: Match[]; competitions: Competition[] };

export function MapsClient() {
  const [data, setData] = useState<AnalyticsData>({ players: [], occurrences: [], actions: [], matches: [], competitions: [] });
  const [playerId, setPlayerId] = useState("all");
  const [actionKey, setActionKey] = useState("all");
  const [competitionId, setCompetitionId] = useState("all");
  const [half, setHalf] = useState<HalfFilter>("all");
  const [matchIds, setMatchIds] = useState<string[]>([]);
  const [matchSelectionMade, setMatchSelectionMade] = useState(false);
  const [mapMode, setMapMode] = useState<MapMode>("normalized");
  const [playlist, setPlaylist] = useState<Playlist>("moments");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [playbackRequest, setPlaybackRequest] = useState(0);

  useEffect(() => { apiFetch<AnalyticsData>("/api/analytics?area=maps").then(setData).catch(() => undefined); }, []);
  const availableMatches = useMemo(() => data.matches.filter((match) => competitionId === "all" || match.competition.id === competitionId), [competitionId, data.matches]);
  useEffect(() => { setMatchIds((current) => current.filter((id) => availableMatches.some((match) => match.id === id))); }, [availableMatches]);

  function commonMatch(item: { playerId: string; matchId: string; period: number | null; match: Match }) {
    return matchSelectionMade && (playerId === "all" || item.playerId === playerId) && (competitionId === "all" || item.match.competition.id === competitionId) && (!matchIds.length || matchIds.includes(item.matchId)) && (half === "all" || item.period === Number(half));
  }
  const moments = useMemo(() => data.occurrences.filter((moment) => commonMatch(moment) && (actionKey === "all" || moment.subActions.some((item) => actionMatchesFilter(item.actionKey, actionKey)))), [data.occurrences, playerId, competitionId, matchIds, matchSelectionMade, half, actionKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const subactions = useMemo(() => data.actions.filter((action) => commonMatch(action) && actionMatchesFilter(action.actionKey, actionKey)), [data.actions, playerId, competitionId, matchIds, matchSelectionMade, half, actionKey]); // eslint-disable-line react-hooks/exhaustive-deps
  const located = useMemo(() => subactions.filter((action) => action.fieldX != null && action.fieldY != null && (mapMode === "original" || action.period !== null)), [subactions, mapMode]);
  const displayed = useMemo(() => located.map((action) => {
    if (mapMode === "original") return action;
    const point = normalizeFieldPoint({ x: action.fieldX!, y: action.fieldY! }, action.period, action.match.firstHalfAttacksRight);
    return { ...action, fieldX: point.x, fieldY: point.y };
  }), [located, mapMode]);
  const playlistItems = useMemo<Array<MapMoment | MapAction>>(() => {
    if (playlist === "moments") return moments;
    if (playlist.startsWith("outcome:")) return subactions.filter((action) => matchesOutcome(action.outcome, playlist.slice(8) as OutcomeFilter));
    return subactions.filter((action) => action.actionKey === playlist.slice(7));
  }, [moments, playlist, subactions]);
  useEffect(() => { if (selectedId && !playlistItems.some((item) => item.id === selectedId)) setSelectedId(null); }, [playlistItems, selectedId]);
  useEffect(() => { setPlaylist("moments"); setSelectedId(null); }, [playerId, actionKey, competitionId, half, matchIds]);

  const selectedIndex = playlistItems.findIndex((item) => item.id === selectedId);
  const selected = selectedIndex >= 0 ? playlistItems[selectedIndex] : null;
  const points = displayed.map((action) => ({ id: action.id, x: action.fieldX!, y: action.fieldY!, color: outcomeColor(action.outcome), active: action.id === selectedId, label: `${action.player.name} · ${actionTypeByKey.get(action.actionKey)?.name || action.actionName}`, details: [`Time: ${formatTime(action.eventTimeSeconds)} · ${action.period === 1 ? "1st half" : action.period === 2 ? "2nd half" : "Period not set"}`, `Match: ${action.match.club.name} vs ${action.match.opponentClub.name}`, `${action.match.competition.season.name} · ${action.match.competition.name}`, mapMode === "normalized" ? "Normalized to left-to-right attack" : "Original saved coordinate"] }));
  const totals = [...new Set(subactions.map((action) => action.actionKey))].map((key) => ({ key, count: subactions.filter((action) => action.actionKey === key).length }));
  const locatedWithoutPeriod = subactions.filter((action) => action.fieldX != null && action.fieldY != null && action.period === null).length;

  function playAction(action: MapMoment | MapAction) { setSelectedId(action.id); setPlaybackRequest((current) => current + 1); }
  function playAll() { setPlaylist("moments"); if (moments[0]) playAction(moments[0]); }
  function playOutcome(outcome: OutcomeFilter) { const next = subactions.filter((action) => matchesOutcome(action.outcome, outcome)); setPlaylist(`outcome:${outcome}`); if (next[0]) playAction(next[0]); else setSelectedId(null); }
  function playType(key: string) { const next = subactions.filter((action) => action.actionKey === key); setPlaylist(`action:${key}`); if (next[0]) playAction(next[0]); else setSelectedId(null); }
  function selectPoint(id: string) { const action = subactions.find((item) => item.id === id); if (!action) return; setPlaylist(`action:${action.actionKey}`); playAction(action); }

  async function exportPdf() {
    const document = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const player = data.players.find((item) => item.id === playerId)?.name || "All players";
    const selectedMatches = data.matches.filter((item) => matchIds.includes(item.id));
    const matchLabel = !matchIds.length ? "All matches" : selectedMatches.length === 1 ? `${selectedMatches[0].club.name} vs ${selectedMatches[0].opponentClub.name}` : `${selectedMatches.length} selected matches`;
    const competition = data.competitions.find((item) => item.id === competitionId);
    document.setFillColor(6, 17, 17); document.rect(0, 0, 297, 210, "F"); document.setTextColor(255, 255, 255); document.setFontSize(20); document.text("Player Action Map", 15, 18);
    document.setFontSize(10); document.setTextColor(170, 200, 200); document.text(`Player: ${player}`, 15, 28); document.text(`Matches: ${matchLabel}`, 15, 34); document.text(`Competition: ${competition ? `${competition.season.name} · ${competition.name}` : "All competitions"}`, 15, 40); document.text(`Action: ${actionFilterName(actionKey)} · ${mapMode === "normalized" ? "normalized left-to-right" : "original coordinates"}`, 15, 46);
    const positive = subactions.filter((item) => item.outcome === "positive").length; const negative = subactions.filter((item) => item.outcome === "negative").length; const neutral = subactions.length - positive - negative;
    document.setTextColor(52, 211, 153); document.text(`Positive: ${positive}`, 220, 28); document.setTextColor(251, 113, 133); document.text(`Negative: ${negative}`, 220, 34); drawPdfPitch(document, 15, 55, 267, 100, displayed);
    document.setTextColor(255, 255, 255); document.setFontSize(11); document.text("Outcome legend", 15, 165); document.setFontSize(9); drawPdfLegendItem(document, 15, 173, "#34d399", `Positive: ${positive}`); drawPdfLegendItem(document, 58, 173, "#fb7185", `Negative: ${negative}`); drawPdfLegendItem(document, 104, 173, "#fbbf24", `Neutral: ${neutral}`);
    document.setTextColor(255, 255, 255); document.setFontSize(11); document.text("Action totals", 15, 184); document.setFontSize(9); let x = 15; const y = 192;
    for (const item of totals) { const label = `${actionTypeByKey.get(item.key)?.name || item.key}: ${item.count}`; const width = document.getTextWidth(label) + 10; if (x + width > 282) break; drawPdfLegendItem(document, x, y, actionTypeByKey.get(item.key)?.color || "#22d3ee", label); x += width; }
    document.save(`player-action-map-${player.replace(/\s+/g, "-").toLowerCase()}.pdf`);
  }

  const playlistTitle = playlist === "moments" ? "Recorded moments" : playlist.startsWith("outcome:") ? `${outcomeLabel(playlist.slice(8) as OutcomeFilter)} subactions` : actionTypeByKey.get(playlist.slice(7))?.name || "Subactions";
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><Label>Spatial analysis</Label><h1 className="mt-2 text-3xl font-bold text-white">Action maps</h1><p className="mt-2 text-sm text-slate-400">Moments remain playable even without subactions or coordinates. Only mapped subactions appear on the pitch.</p></div><Button variant="primary" disabled={!displayed.length} onClick={() => void exportPdf()}><Download size={16}/>Export map PDF</Button></div>
    <Panel className="relative z-40 grid overflow-visible gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><Filter label="Player / moment" value={playerId} onChange={setPlayerId}><option value="all">All players</option>{data.players.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</Filter><Filter label="Subaction" value={actionKey} onChange={setActionKey}><option value="all">All subactions</option><ActionFilterOptions/></Filter><Filter label="Competition" value={competitionId} onChange={setCompetitionId}><option value="all">All competitions</option>{data.competitions.map((competition) => <option key={competition.id} value={competition.id}>{competition.season.name} · {competition.name}</option>)}</Filter><Filter label="Half" value={half} onChange={(value) => setHalf(value as HalfFilter)}><option value="all">Full match</option><option value="1">First half</option><option value="2">Second half</option></Filter><MatchMultiSelect matches={availableMatches} value={matchIds} selectionMade={matchSelectionMade} onChange={(next) => { setMatchIds(next); setMatchSelectionMade(true); }}/></Panel>
    {matchSelectionMade ? <div className="grid gap-3 sm:grid-cols-3"><Summary label="Recorded moments" value={moments.length}/><Summary label="Identified subactions" value={subactions.length}/><Summary label="Mapped subactions" value={located.length}/></div> : null}
    {matchSelectionMade && moments.length > 0 && located.length === 0 ? <div className="rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100">{moments.length} recorded {moments.length === 1 ? "moment is" : "moments are"} available to play, but no matching subaction has coordinates yet.</div> : null}
    {mapMode === "normalized" && locatedWithoutPeriod ? <div className="rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100">{locatedWithoutPeriod} mapped {locatedWithoutPeriod === 1 ? "subaction is" : "subactions are"} waiting for match period markers. Switch to Original to view saved coordinates now.</div> : null}
    <div className="relative z-0 grid items-start gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(20rem,.65fr)]">
      <Panel className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><Label>Pitch · mapped subactions</Label><p className="mt-1 text-xs text-slate-500">{matchSelectionMade ? `${displayed.length} coordinates shown` : "Select at least one match above."}</p></div><div className="flex items-center gap-2"><div className="flex overflow-hidden rounded-md border border-white/10"><button type="button" onClick={() => setMapMode("original")} className={`h-8 px-3 text-[10px] font-semibold ${mapMode === "original" ? "bg-cyan-300 text-slate-950" : "bg-white/[.04] text-slate-300"}`}>Original</button><button type="button" onClick={() => setMapMode("normalized")} className={`h-8 px-3 text-[10px] font-semibold ${mapMode === "normalized" ? "bg-cyan-300 text-slate-950" : "bg-white/[.04] text-slate-300"}`}>Same attack direction</button></div><MapPinned className="text-cyan-300"/></div></div><Pitch className="mt-4" points={points} onPointSelect={selectPoint}/></Panel>
      <div data-video-workspace className="space-y-3"><ActionClipPlayer key={playbackRequest} area="maps" action={selected} onClipEnd={selectedIndex >= 0 && selectedIndex < playlistItems.length - 1 ? () => setSelectedId(playlistItems[selectedIndex + 1].id) : undefined}/><Panel className="overflow-hidden"><div className="border-b border-white/10 p-3"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><Label>{playlistTitle}</Label><p className="mt-1 truncate text-xs text-slate-500">{playlist === "moments" ? "All recorded moments matching the filters" : "Identified subactions matching this playlist"}</p></div><Badge>{playlistItems.length}</Badge></div><div className="mt-3 flex gap-2"><Button size="sm" variant="primary" className="flex-1" disabled={!moments.length} onClick={playAll}><Play size={14}/>Play all moments</Button>{playlist !== "moments" ? <Button size="sm" onClick={() => { setPlaylist("moments"); setSelectedId(null); }}>Show moments</Button> : null}</div></div><div className="max-h-80 divide-y divide-white/[.06] overflow-y-auto">{playlistItems.length ? playlistItems.map((item) => <button key={item.id} type="button" onClick={() => playAction(item)} className={`flex w-full items-center gap-2 p-2.5 text-left transition hover:bg-white/[.06] ${selectedId === item.id ? "bg-cyan-300/10" : ""}`}><Play size={13} className="shrink-0 text-cyan-300"/><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: item.outcome ? outcomeColor(item.outcome) : "#64748b" }}/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-white">{item.player.name}{"subActions" in item ? " · Recorded moment" : ` · ${actionTypeByKey.get(item.actionKey)?.name || item.actionName}`}</span><span className="block truncate text-[10px] text-slate-500">{item.match.club.name} vs {item.match.opponentClub.name} · {formatTime(item.eventTimeSeconds)}</span></span></button>) : <div className="p-6 text-center text-xs text-slate-500"><ListVideo className="mx-auto mb-2"/>No clips match this playlist.</div>}</div></Panel></div>
    </div>
    <Panel className="p-4"><div className="flex items-center justify-between"><div><Label>Subaction playlists</Label><p className="mt-1 text-xs text-slate-500">Choose a result or action type to play all matching identified clips</p></div><Badge>{subactions.length} subactions</Badge></div><div className="mt-3 flex flex-wrap gap-2"><LegendItem color="#34d399" label="Positive" count={subactions.filter((action) => action.outcome === "positive").length} active={playlist === "outcome:positive"} onClick={() => playOutcome("positive")}/><LegendItem color="#fb7185" label="Negative" count={subactions.filter((action) => action.outcome === "negative").length} active={playlist === "outcome:negative"} onClick={() => playOutcome("negative")}/><LegendItem color="#fbbf24" label="Neutral" count={subactions.filter((action) => !action.outcome || action.outcome === "neutral").length} active={playlist === "outcome:neutral"} onClick={() => playOutcome("neutral")}/></div><Label className="mt-5 block">Subaction totals</Label><div className="mt-2 flex flex-wrap gap-2">{totals.map(({ key, count }) => <button type="button" key={key} onClick={() => playType(key)} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs transition ${playlist === `action:${key}` ? "border-cyan-300/50 bg-cyan-300/15 text-white" : "border-white/10 bg-white/[.04] text-slate-300 hover:bg-white/[.08]"}`}><Play size={11}/>{actionTypeByKey.get(key)?.name || key}<strong className="text-white">{count}</strong></button>)}</div></Panel>
    <GameComparison data={data} playerId={playerId} actionKey={actionKey} competitionId={competitionId}/>
  </div>;
}

function GameComparison({ data, playerId, actionKey, competitionId }: { data: AnalyticsData; playerId: string; actionKey: string; competitionId: string }) {
  const matches = data.matches.filter((match) => competitionId === "all" || match.competition.id === competitionId);
  const [firstId, setFirstId] = useState(""); const [secondId, setSecondId] = useState(""); const [half, setHalf] = useState<HalfFilter>("all");
  useEffect(() => { setFirstId((id) => matches.some((match) => match.id === id) ? id : matches[0]?.id || ""); setSecondId((id) => matches.some((match) => match.id === id && match.id !== firstId) ? id : matches.find((match) => match.id !== firstId)?.id || ""); }, [competitionId, data.matches, firstId]); // eslint-disable-line react-hooks/exhaustive-deps
  const first = comparisonStats(data, firstId, playerId, actionKey, half); const second = comparisonStats(data, secondId, playerId, actionKey, half);
  const rows: Array<[string, number, number, string?]> = [["Recorded moments", first.moments, second.moments], ["Mapped occurrences", first.located, second.located], ["Identified subactions", first.subactions, second.subactions], ["Positive", first.positive, second.positive], ["Negative", first.negative, second.negative], ["Moments per 90", first.per90, second.per90, "decimal"]];
  return <Panel className="p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><Label>Compare games</Label><h2 className="mt-1 text-lg font-bold text-white">Moment and subaction comparison</h2><p className="mt-1 text-xs text-slate-500">Totals are based on every recorded moment; coordinates are reported separately.</p></div><div className="grid w-full gap-2 sm:grid-cols-3 xl:w-auto xl:min-w-[48rem]"><Filter label="Game A" value={firstId} onChange={setFirstId}><option value="">Select game</option>{matches.filter((match) => match.id !== secondId).map((match) => <option key={match.id} value={match.id}>{match.club.name} vs {match.opponentClub.name}</option>)}</Filter><Filter label="Game B" value={secondId} onChange={setSecondId}><option value="">Select game</option>{matches.filter((match) => match.id !== firstId).map((match) => <option key={match.id} value={match.id}>{match.club.name} vs {match.opponentClub.name}</option>)}</Filter><Filter label="Half" value={half} onChange={(value) => setHalf(value as HalfFilter)}><option value="all">Full match</option><option value="1">First half</option><option value="2">Second half</option></Filter></div></div>{firstId && secondId ? <div className="mt-4 overflow-hidden rounded-md border border-white/10"><div className="grid grid-cols-[minmax(9rem,1fr)_minmax(7rem,1fr)_minmax(7rem,1fr)] bg-white/[.04] px-3 py-2 text-[10px] font-semibold uppercase tracking-wide text-slate-500"><span>Metric</span><span className="text-center">Game A</span><span className="text-center">Game B</span></div>{rows.map(([label, a, b, format]) => { const max = Math.max(a, b, 1); return <div key={label} className="grid grid-cols-[minmax(9rem,1fr)_minmax(7rem,1fr)_minmax(7rem,1fr)] items-center gap-3 border-t border-white/[.06] px-3 py-2"><span className="text-xs text-slate-300">{label}</span><ComparisonValue value={a} max={max} decimal={format === "decimal"}/><ComparisonValue value={b} max={max} decimal={format === "decimal"}/></div>; })}</div> : <p className="mt-4 rounded-md border border-dashed border-white/10 p-5 text-center text-xs text-slate-500">Select two different games to compare them.</p>}</Panel>;
}

function comparisonStats(data: AnalyticsData, matchId: string, playerId: string, actionKey: string, half: HalfFilter) { const match = data.matches.find((item) => item.id === matchId); const periodMatches = (period: number | null) => half === "all" || period === Number(half); const moments = data.occurrences.filter((item) => item.matchId === matchId && (playerId === "all" || item.playerId === playerId) && periodMatches(item.period) && (actionKey === "all" || item.subActions.some((subaction) => actionMatchesFilter(subaction.actionKey, actionKey)))); const actions = data.actions.filter((item) => item.matchId === matchId && (playerId === "all" || item.playerId === playerId) && periodMatches(item.period) && actionMatchesFilter(item.actionKey, actionKey)); const minutes = match ? matchMinutes(match, half) : half === "all" ? 90 : 45; return { moments: moments.length, located: actions.filter((item) => item.fieldX != null && item.fieldY != null).length, subactions: actions.length, positive: actions.filter((item) => item.outcome === "positive").length, negative: actions.filter((item) => item.outcome === "negative").length, per90: minutes ? moments.length * 90 / minutes : 0 }; }
function matchMinutes(match: Match, half: HalfFilter) { const first = markedMinutes(match.firstHalfStartSeconds, match.firstHalfEndSeconds, 45); const second = markedMinutes(match.secondHalfStartSeconds, match.secondHalfEndSeconds, 45); return half === "1" ? first : half === "2" ? second : first + second; }
function markedMinutes(start: number | null, end: number | null, fallback: number) { return start !== null && end !== null && end > start ? (end - start) / 60 : fallback; }
function ComparisonValue({ value, max, decimal }: { value: number; max: number; decimal: boolean }) { return <span className="relative overflow-hidden rounded bg-black/20 px-2 py-1.5 text-center font-mono text-xs text-white"><span className="absolute inset-y-0 left-0 bg-cyan-300/15" style={{ width: `${value / max * 100}%` }}/><span className="relative">{decimal ? value.toFixed(1) : value}</span></span>; }
function Summary({ label, value }: { label: string; value: number }) { return <Panel className="p-3"><Label>{label}</Label><p className="mt-1 text-2xl font-bold text-white">{value}</p></Panel>; }
function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label><Label>{label}</Label><Select className="mt-1" value={value} onChange={(event) => onChange(event.target.value)}>{children}</Select></label>; }
function ActionFilterOptions() { return <>{actionFilterGroups.flatMap((group) => [<option key={group.key} value={group.key}>{group.name}</option>, ...group.actionKeys.map((key) => { const action = actionTypeByKey.get(key); return action ? <option key={key} value={key}>　↳ {action.name}</option> : null; })])}{standaloneActionTypes.map((action) => <option key={action.key} value={action.key}>{action.name}</option>)}</>; }
function MatchMultiSelect({ matches, value, selectionMade, onChange }: { matches: Match[]; value: string[]; selectionMade: boolean; onChange: (value: string[]) => void }) { const selected = new Set(value); const label = !selectionMade ? "Select matches" : value.length === 0 ? "All matches" : value.length === 1 ? "1 match selected" : `${value.length} matches selected`; function toggle(id: string) { onChange(selected.has(id) ? value.filter((item) => item !== id) : [...value, id]); } const allSelected = selectionMade && value.length === 0; return <div className="relative z-50 min-w-0"><Label>Matches</Label><details className="group relative mt-1"><summary className="flex h-10 cursor-pointer list-none items-center justify-between rounded-md border border-white/10 bg-pitch-950 px-3 text-sm text-slate-200 [&::-webkit-details-marker]:hidden"><span className="truncate">{label}</span><span className="ml-2 text-[10px] text-slate-500">{!selectionMade ? "—" : value.length || "ALL"} ▾</span></summary><div className="absolute right-0 z-[60] mt-1 w-full min-w-72 overflow-hidden rounded-lg border border-white/10 bg-pitch-950 shadow-2xl"><button type="button" onClick={() => onChange([])} className={`flex w-full items-center gap-2 border-b border-white/10 px-3 py-2 text-left text-xs ${allSelected ? "bg-cyan-300/10 text-cyan-100" : "text-slate-300 hover:bg-white/[.06]"}`}><span className={`flex h-4 w-4 items-center justify-center rounded border ${allSelected ? "border-cyan-300 bg-cyan-300 text-slate-950" : "border-white/20"}`}>{allSelected ? "✓" : ""}</span>All matches</button><div className="max-h-64 overflow-y-auto">{matches.map((match) => { const checked = selected.has(match.id); return <button key={match.id} type="button" onClick={() => toggle(match.id)} className={`flex w-full items-start gap-2 border-b border-white/[.05] px-3 py-2 text-left ${checked ? "bg-cyan-300/10" : "hover:bg-white/[.05]"}`}><span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border text-[10px] ${checked ? "border-cyan-300 bg-cyan-300 text-slate-950" : "border-white/20"}`}>{checked ? "✓" : ""}</span><span className="min-w-0"><span className="block truncate text-xs font-semibold text-white">{match.club.name} vs {match.opponentClub.name}</span><span className="block truncate text-[10px] text-slate-500">{match.competition.season.name} · {match.competition.name}</span></span></button>; })}</div></div></details></div>; }
function LegendItem({ color, label, count, active, onClick }: { color: string; label: string; count: number; active: boolean; onClick: () => void }) { return <button type="button" disabled={!count} aria-pressed={active} onClick={onClick} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs transition disabled:opacity-40 ${active ? "border-cyan-300/50 bg-cyan-300/15 text-white" : "border-white/10 bg-white/[.04] text-slate-300 hover:bg-white/[.08]"}`}><Play size={11}/><span className="h-3 w-3 rounded-full" style={{ backgroundColor: color }}/>{label}<strong className="text-white">{count}</strong></button>; }
function matchesOutcome(outcome: string | null, filter: OutcomeFilter) { return filter === "neutral" ? !outcome || outcome === "neutral" : outcome === filter; }
function outcomeLabel(outcome: OutcomeFilter) { return outcome === "positive" ? "Positive" : outcome === "negative" ? "Negative" : "Neutral"; }
function outcomeColor(outcome: string | null) { return outcome === "positive" ? "#34d399" : outcome === "negative" ? "#fb7185" : "#fbbf24"; }
function hexToRgb(hex: string): [number, number, number] { const value = hex.replace("#", ""); return [parseInt(value.slice(0, 2), 16), parseInt(value.slice(2, 4), 16), parseInt(value.slice(4, 6), 16)]; }
function drawPdfLegendItem(document: jsPDF, x: number, y: number, color: string, label: string) { document.setFillColor(...hexToRgb(color)); document.circle(x + 2, y - 1, 1.5, "F"); document.setTextColor(220, 235, 235); document.text(label, x + 6, y); }
function drawPdfPitch(document: jsPDF, x: number, y: number, width: number, height: number, actions: MapAction[]) { document.setFillColor(22, 118, 65); document.roundedRect(x, y, width, height, 2, 2, "F"); document.setDrawColor(255, 255, 255); document.setLineWidth(.4); document.rect(x + 2, y + 2, width - 4, height - 4); document.line(x + width / 2, y + 2, x + width / 2, y + height - 2); document.circle(x + width / 2, y + height / 2, height * .14); document.rect(x + 2, y + height * .2, width * .16, height * .6); document.rect(x + width * .84 - 2, y + height * .2, width * .16, height * .6); for (const action of actions) { const [r, g, b] = hexToRgb(outcomeColor(action.outcome)); document.setFillColor(r, g, b); document.setDrawColor(255, 255, 255); document.circle(x + (action.fieldX! / 100) * width, y + (action.fieldY! / 100) * height, 2, "FD"); } }
