"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Save } from "lucide-react";
import Link from "next/link";
import { apiFetch } from "@/lib/http";
import { Button, Input, Label, Panel, Select, TextArea } from "@/components/ui";

type Club = { id: string; name: string };
type Competition = { id: string; name: string; clubs: Club[] };
type Season = { id: string; name: string; competitions: Competition[] };
export function NewMatchForm() {
  const router = useRouter(); const [seasons, setSeasons] = useState<Season[]>([]); const [clientClub, setClientClub] = useState<Club | null>(null); const [competitionId, setCompetitionId] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiFetch<{ seasons: Season[]; clientClub: Club | null }>("/api/structure").then((data) => { setSeasons(data.seasons); setClientClub(data.clientClub); setCompetitionId(data.seasons.flatMap((season) => season.competitions)[0]?.id || ""); }).catch((caught) => setError(caught.message)); }, []);
  const competitions = useMemo(() => seasons.flatMap((season) => season.competitions.map((competition) => ({ ...competition, seasonName: season.name }))), [seasons]);
  const opponents = competitions.find((competition) => competition.id === competitionId)?.clubs || [];
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const match = await apiFetch<{ id: string }>("/api/matches", { method: "POST", body: JSON.stringify({ ...data, competitionId }) }); router.push(`/analysis/${match.id}`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível criar o jogo."); setBusy(false); } }
  return <div className="mx-auto max-w-3xl"><Link href="/" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-white"><ArrowLeft size={14}/>Jogos</Link><div className="mt-4"><Label>Novo registo</Label><h1 className="mt-2 text-3xl font-bold text-white">Criar jogo</h1><p className="mt-2 text-sm text-slate-400">A equipa analisada é sempre {clientClub?.name || "a equipa do cliente"}. O nome do jogo é gerado automaticamente.</p></div><Panel className="mt-5 p-5"><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => void submit(event)}><Field label="Competição"><Select value={competitionId} onChange={(event) => setCompetitionId(event.target.value)} required><option value="">Selecionar</option>{competitions.map((competition) => <option value={competition.id} key={competition.id}>{competition.seasonName} · {competition.name}</option>)}</Select></Field><Field label="Equipa adversária"><Select name="opponentClubId" required><option value="">Selecionar</option>{opponents.map((club) => <option value={club.id} key={club.id}>{club.name}</option>)}</Select></Field><Field label="Data"><Input name="matchDate" type="date"/></Field><Field label="Jornada"><Input name="roundName" placeholder="Jornada 1"/></Field><Field label="Local"><Input name="venue" placeholder="Estádio / campo"/></Field><div className="sm:col-span-2"><Field label="Notas"><TextArea name="notes" placeholder="Observações sobre o jogo"/></Field></div>{error ? <p className="text-sm text-red-300 sm:col-span-2">{error}</p> : null}<div className="flex justify-end sm:col-span-2"><Button variant="primary" disabled={busy || !clientClub || opponents.length === 0}><Save size={15}/>{busy ? "A guardar…" : "Criar e analisar"}</Button></div></form>{!clientClub ? <p className="mt-4 text-sm text-amber-200">Configura a equipa do cliente na área Plantel.</p> : competitions.length === 0 ? <p className="mt-4 text-sm text-amber-200">Cria uma época e uma competição antes de adicionar um jogo.</p> : opponents.length === 0 ? <p className="mt-4 text-sm text-amber-200">Adiciona pelo menos um adversário à competição selecionada.</p> : null}</Panel></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label>{label}</Label><div className="mt-1">{children}</div></div>; }
