"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Film, UserRound, XCircle } from "lucide-react";
import { allActionTypes, actionTypeByKey } from "@/lib/action-types";
import { apiFetch } from "@/lib/http";
import { Label, Panel, Select } from "@/components/ui";

type Player = { id: string; name: string; photoUrl: string | null; club: { name: string } };
type ReportAction = { id: string; playerId: string; actionKey: string; actionName: string; outcome: string | null; matchId: string; player: Player; match: { title: string; competition: { name: string; season: { name: string } } } };
export function ReportsClient() {
  const [data, setData] = useState<{ players: Player[]; actions: ReportAction[] }>({ players: [], actions: [] }); const [playerId, setPlayerId] = useState("all"); const [actionKey, setActionKey] = useState("all"); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiFetch<typeof data>("/api/analytics").then(setData).catch((e) => setError(e.message)); }, []);
  const filtered = useMemo(() => data.actions.filter((a) => (playerId === "all" || a.playerId === playerId) && (actionKey === "all" || a.actionKey === actionKey)), [data.actions, playerId, actionKey]);
  const byPlayer = useMemo(() => data.players.map((player) => ({ player, actions: filtered.filter((a) => a.playerId === player.id) })).filter((row) => row.actions.length > 0).sort((a, b) => b.actions.length - a.actions.length), [data.players, filtered]);
  const byType = useMemo(() => [...new Set(filtered.map((a) => a.actionKey))].map((key) => ({ key, name: actionTypeByKey.get(key)?.name || key, count: filtered.filter((a) => a.actionKey === key).length })).sort((a, b) => b.count - a.count), [filtered]);
  const positive = filtered.filter((a) => a.outcome === "positive").length; const negative = filtered.filter((a) => a.outcome === "negative").length;
  return <div className="space-y-5"><div><Label>Dados agregados</Label><h1 className="mt-2 text-3xl font-bold text-white">Relatórios de jogadores</h1><p className="mt-2 text-sm text-slate-400">Totais construídos diretamente a partir das ações classificadas nos vídeos.</p></div>{error ? <p className="text-red-300">{error}</p> : null}<Panel className="grid gap-3 p-4 sm:grid-cols-2"><div><Label>Jogador</Label><Select className="mt-1" value={playerId} onChange={(e) => setPlayerId(e.target.value)}><option value="all">Todos os jogadores</option>{data.players.map((p) => <option key={p.id} value={p.id}>{p.name} · {p.club.name}</option>)}</Select></div><div><Label>Ação</Label><Select className="mt-1" value={actionKey} onChange={(e) => setActionKey(e.target.value)}><option value="all">Todas as ações</option>{allActionTypes.map((a) => <option key={a.key} value={a.key}>{a.name}</option>)}</Select></div></Panel><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Activity} label="Ações" value={filtered.length}/><Metric icon={Film} label="Jogos analisados" value={new Set(filtered.map((a) => a.matchId)).size}/><Metric icon={CheckCircle2} label="Positivas" value={positive}/><Metric icon={XCircle} label="Negativas" value={negative}/></div><div className="grid gap-4 xl:grid-cols-2"><Panel className="p-4"><Label>Por jogador</Label><div className="mt-4 space-y-3">{byPlayer.map(({ player, actions }) => <Bar key={player.id} label={player.name} sublabel={player.club.name} value={actions.length} max={Math.max(1, byPlayer[0]?.actions.length || 1)}/>)}</div></Panel><Panel className="p-4"><Label>Por tipo de ação</Label><div className="mt-4 space-y-3">{byType.map((type) => <Bar key={type.key} label={type.name} value={type.count} max={Math.max(1, byType[0]?.count || 1)} color={actionTypeByKey.get(type.key)?.color}/>)}</div></Panel></div></div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value: number }) { return <Panel className="p-4"><div className="flex items-center justify-between"><Label>{label}</Label><Icon size={18} className="text-cyan-300"/></div><p className="mt-3 text-3xl font-bold text-white">{value}</p></Panel>; }
function Bar({ label, sublabel, value, max, color = "#22d3ee" }: { label: string; sublabel?: string; value: number; max: number; color?: string }) { return <div><div className="flex justify-between gap-3 text-sm"><span className="truncate text-slate-200">{label}{sublabel ? <span className="ml-2 text-xs text-slate-500">{sublabel}</span> : null}</span><strong>{value}</strong></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full" style={{ width: `${(value / max) * 100}%`, backgroundColor: color }}/></div></div>; }
