"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Film, Play, UserRound, XCircle } from "lucide-react";
import { allActionTypes, actionTypeByKey } from "@/lib/action-types";
import { apiFetch } from "@/lib/http";
import { formatTime } from "@/lib/time";
import { ActionClipPlayer, type ClipAction } from "@/components/action-clip-player";
import { Badge, Label, Panel, Select } from "@/components/ui";

type Player = { id: string; name: string; club: { name: string } };
type Match = { id: string; roundName: string | null; club: { name: string }; opponentClub: { name: string }; competition: { id: string; name: string; season: { name: string } }; video: { fileName: string } | null };
type ReportAction = ClipAction & { playerId: string; actionKey: string; outcome: string | null; matchId: string; match: Match };
type Competition = { id: string; name: string; season: { name: string } };
export function ReportsClient() {
  const [data, setData] = useState<{ players: Player[]; actions: ReportAction[]; matches: Match[]; competitions: Competition[] }>({ players: [], actions: [], matches: [], competitions: [] });
  const [playerId, setPlayerId] = useState("all"); const [actionKey, setActionKey] = useState("all"); const [competitionId, setCompetitionId] = useState("all"); const [matchId, setMatchId] = useState("all"); const [selectedId, setSelectedId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiFetch<typeof data>("/api/analytics").then(setData).catch((caught) => setError(caught.message)); }, []);
  const availableMatches = useMemo(() => data.matches.filter((match) => competitionId === "all" || match.competition.id === competitionId), [competitionId, data.matches]);
  useEffect(() => { if (matchId !== "all" && !availableMatches.some((match) => match.id === matchId)) setMatchId("all"); }, [availableMatches, matchId]);
  const filtered = useMemo(() => data.actions.filter((action) => (playerId === "all" || action.playerId === playerId) && (actionKey === "all" || action.actionKey === actionKey) && (competitionId === "all" || action.match.competition.id === competitionId) && (matchId === "all" || action.matchId === matchId)), [data.actions, playerId, actionKey, competitionId, matchId]);
  useEffect(() => { if (selectedId && !filtered.some((action) => action.id === selectedId)) setSelectedId(null); }, [filtered, selectedId]);
  const selected = filtered.find((action) => action.id === selectedId) || null; const positive = filtered.filter((action) => action.outcome === "positive").length; const negative = filtered.filter((action) => action.outcome === "negative").length;
  return <div className="space-y-5"><div><Label>Análise agregada</Label><h1 className="mt-2 text-3xl font-bold text-white">Relatórios e lances</h1><p className="mt-2 text-sm text-slate-400">Filtra as ações e seleciona qualquer ocorrência para rever o respetivo lance de vídeo.</p></div>{error ? <p className="text-red-300">{error}</p> : null}
    <Panel className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><Filter label="Jogador" value={playerId} onChange={setPlayerId}><option value="all">Todos os jogadores</option>{data.players.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</Filter><Filter label="Ação" value={actionKey} onChange={setActionKey}><option value="all">Todas as ações</option>{allActionTypes.map((action) => <option key={action.key} value={action.key}>{action.name}</option>)}</Filter><Filter label="Competição" value={competitionId} onChange={setCompetitionId}><option value="all">Todas as competições</option>{data.competitions.map((competition) => <option key={competition.id} value={competition.id}>{competition.season.name} · {competition.name}</option>)}</Filter><Filter label="Jogo" value={matchId} onChange={setMatchId}><option value="all">Todos os jogos</option>{availableMatches.map((match) => <option key={match.id} value={match.id}>{match.club.name} vs {match.opponentClub.name}</option>)}</Filter></Panel>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Activity} label="Ações filtradas" value={filtered.length}/><Metric icon={Film} label="Jogos" value={new Set(filtered.map((action) => action.matchId)).size}/><Metric icon={CheckCircle2} label="Positivas" value={positive}/><Metric icon={XCircle} label="Negativas" value={negative}/></div>
    <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_24rem]"><ActionClipPlayer action={selected}/><Panel className="overflow-hidden xl:max-h-[42rem]"><div className="flex items-center justify-between border-b border-white/10 p-3"><div><Label>Ações dos filtros</Label><p className="mt-1 text-xs text-slate-500">Clica para ver o lance</p></div><Badge>{filtered.length}</Badge></div><div className="max-h-[36rem] divide-y divide-white/[.06] overflow-y-auto">{filtered.length ? filtered.map((action) => <button key={action.id} onClick={() => setSelectedId(action.id)} className={`flex w-full items-center gap-3 p-3 text-left transition hover:bg-white/[.06] ${selectedId === action.id ? "bg-cyan-300/10" : ""}`}><Play size={15} className="shrink-0 text-cyan-300"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-white">{action.player.name} · {action.actionName}</span><span className="block truncate text-xs text-slate-500">{action.match.club.name} vs {action.match.opponentClub.name} · {formatTime(action.eventTimeSeconds)}</span></span><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: actionTypeByKey.get(action.actionKey)?.color }}/></button>) : <div className="p-10 text-center text-sm text-slate-500"><Film className="mx-auto mb-3"/>Não existem ações para estes filtros.</div>}</div></Panel></div>
  </div>;
}
function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label><Label>{label}</Label><Select className="mt-1" value={value} onChange={(event) => onChange(event.target.value)}>{children}</Select></label>; }
function Metric({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value: number }) { return <Panel className="p-4"><div className="flex items-center justify-between"><Label>{label}</Label><Icon size={18} className="text-cyan-300"/></div><p className="mt-3 text-3xl font-bold text-white">{value}</p></Panel>; }
