"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Plus, Shield, Trash2, Trophy, UserRound, UsersRound } from "lucide-react";
import { apiFetch } from "@/lib/http";
import { Button, Input, Label, Panel, Select } from "@/components/ui";

type Player = { id: string; name: string; shirtNumber: number | null; photoUrl: string | null; position: string | null; isGoalkeeper: boolean };
type Club = { id: string; name: string; shortName: string | null; badgeUrl: string | null; players?: Player[]; competitions?: Array<{ id: string; name: string }> };
type Competition = { id: string; name: string; clubs: Club[] };
type Season = { id: string; name: string; competitions: Competition[] };
type Data = { clientClub: Club | null; seasons: Season[]; opponents: Club[] };
const positions = ["Guarda-Redes", "Defesa Direito", "Defesa Esquerdo", "Defesa Central", "Lateral Direito", "Lateral Esquerdo", "Médio Defensivo", "Médio Centro", "Médio Ofensivo", "Extremo Direito", "Extremo Esquerdo", "Avançado", "Ponta de Lança"];

export function StructureClient() {
  const [data, setData] = useState<Data>({ clientClub: null, seasons: [], opponents: [] }); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const [seasonId, setSeasonId] = useState(""); const [competitionId, setCompetitionId] = useState("");
  const load = useCallback(async () => { try { const result = await apiFetch<Data>("/api/structure"); setData(result); setSeasonId((value) => result.seasons.some((item) => item.id === value) ? value : result.seasons[0]?.id || ""); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível carregar."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const competitions = useMemo(() => data.seasons.find((season) => season.id === seasonId)?.competitions || [], [data.seasons, seasonId]);
  useEffect(() => { if (!competitions.some((item) => item.id === competitionId)) setCompetitionId(competitions[0]?.id || ""); }, [competitions, competitionId]);
  const selectedCompetition = competitions.find((item) => item.id === competitionId) || null;

  async function submit(event: FormEvent<HTMLFormElement>, kind: string) {
    event.preventDefault(); setBusy(true); setNotice(null); const formElement = event.currentTarget; const body = Object.fromEntries(new FormData(formElement));
    try { await apiFetch("/api/structure", { method: "POST", body: JSON.stringify({ ...body, kind, seasonId, competitionId, isGoalkeeper: body.isGoalkeeper === "on" }) }); if (kind !== "clientClub") formElement.reset(); setNotice("Guardado com sucesso."); await load(); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível guardar."); } finally { setBusy(false); }
  }
  async function remove(resource: string, id: string, label: string) { if (!confirm(`Eliminar ${label}? Os dados dependentes também podem ser eliminados.`)) return; try { await apiFetch(`/api/structure/${resource}/${id}`, { method: "DELETE" }); await load(); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível eliminar."); } }

  return <div className="space-y-5">
    <div><Label>Configuração privada</Label><h1 className="mt-2 text-3xl font-bold text-white">Equipa, competições e adversários</h1><p className="mt-2 text-sm text-slate-400">A equipa do cliente é sempre analisada e é a única que pode ter jogadores. As outras equipas são apenas adversários.</p></div>
    {notice ? <div className="rounded-lg border border-cyan-300/20 bg-cyan-300/10 px-4 py-3 text-sm text-cyan-100">{notice}</div> : null}
    <Panel className="p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-cyan-300/10 text-cyan-200"><Shield/></span><div><Label>Equipa do cliente</Label><h2 className="mt-1 text-xl font-bold text-white">{data.clientClub?.name || "Configura a equipa que será sempre analisada"}</h2></div></div><form key={data.clientClub?.id || "new-client"} className="mt-5 grid gap-3 md:grid-cols-[1fr_.45fr_1fr_auto] md:items-end" onSubmit={(event) => void submit(event, "clientClub")}><Field label="Nome"><Input name="name" defaultValue={data.clientClub?.name} required placeholder="Nome da equipa"/></Field><Field label="Nome curto"><Input name="shortName" defaultValue={data.clientClub?.shortName || ""} placeholder="Sigla"/></Field><Field label="Link do emblema"><Input name="badgeUrl" type="url" defaultValue={data.clientClub?.badgeUrl || ""} placeholder="https://…"/></Field><Button variant="primary" disabled={busy}>{data.clientClub ? "Guardar equipa" : "Criar equipa"}</Button></form>{data.clientClub ? <p className="mt-3 text-xs text-slate-500">Associada automaticamente a todas as competições desta conta.</p> : null}</Panel>
    <div className="grid gap-4 xl:grid-cols-4">
      <Panel className="p-4"><Heading icon={Trophy} title="1. Época"/><form className="mt-4 space-y-3" onSubmit={(event) => void submit(event, "season")}><Field label="Nome"><Input name="name" placeholder="2026/27" required/></Field><Button variant="primary" className="w-full" disabled={busy}><Plus size={15}/>Adicionar época</Button></form><div className="mt-5 space-y-2">{data.seasons.map((season) => <Row key={season.id} active={season.id === seasonId} label={season.name} onClick={() => setSeasonId(season.id)} onDelete={() => void remove("season", season.id, season.name)}/>)}</div></Panel>
      <Panel className="p-4"><Heading icon={Shield} title="2. Competição"/><form className="mt-4 space-y-3" onSubmit={(event) => void submit(event, "competition")}><Field label="Nome"><Input name="name" placeholder="Liga 3" required/></Field><Button variant="primary" className="w-full" disabled={busy || !seasonId}><Plus size={15}/>Adicionar competição</Button></form><div className="mt-5 space-y-2">{competitions.map((competition) => <Row key={competition.id} active={competition.id === competitionId} label={competition.name} onClick={() => setCompetitionId(competition.id)} onDelete={() => void remove("competition", competition.id, competition.name)}/>)}</div></Panel>
      <Panel className="p-4"><Heading icon={Building2} title="3. Adversário"/><form className="mt-4 space-y-3" onSubmit={(event) => void submit(event, "opponent")}><Field label="Nome"><Input name="name" placeholder="Equipa adversária" required/></Field><Field label="Nome curto"><Input name="shortName" placeholder="Sigla"/></Field><Field label="Link do emblema"><Input name="badgeUrl" type="url" placeholder="https://…"/></Field><Button variant="primary" className="w-full" disabled={busy || !competitionId}><Plus size={15}/>Adicionar à competição</Button></form><div className="mt-5 space-y-2">{selectedCompetition?.clubs.map((club) => <Row key={club.id} label={club.name} active={false} onDelete={() => void remove("opponent", club.id, club.name)}/>)}</div></Panel>
      <Panel className="p-4"><Heading icon={UsersRound} title="4. Jogador"/><form className="mt-4 space-y-3" onSubmit={(event) => void submit(event, "player")}><Field label="Nome"><Input name="name" placeholder="Nome completo" required/></Field><div className="grid grid-cols-2 gap-2"><Field label="Número"><Input name="shirtNumber" type="number" min="1" max="99"/></Field><Field label="Posição"><Select name="position"><option value="">Selecionar</option>{positions.map((position) => <option key={position}>{position}</option>)}</Select></Field></div><Field label="Link da fotografia"><Input name="photoUrl" type="url" placeholder="https://…"/></Field><label className="flex items-center gap-2 text-sm text-slate-300"><input name="isGoalkeeper" type="checkbox" className="accent-cyan-300"/> Guarda-redes</label><Button variant="primary" className="w-full" disabled={busy || !data.clientClub}><Plus size={15}/>Adicionar jogador</Button></form></Panel>
    </div>
    <Panel className="p-4"><div className="flex items-center justify-between"><div><Label>Plantel da equipa do cliente</Label><h2 className="mt-1 text-xl font-bold text-white">{data.clientClub?.name || "Configura primeiro a equipa"}</h2></div><UserRound className="text-cyan-300"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-6">{data.clientClub?.players?.map((player) => <div key={player.id} className="flex items-center gap-3 rounded-lg border border-white/10 bg-black/15 p-2"><PlayerPhoto player={player}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-white">{player.shirtNumber ? `${player.shirtNumber} · ` : ""}{player.name}</p><p className="truncate text-xs text-slate-500">{player.position || "Sem posição"}</p></div><button aria-label="Eliminar jogador" onClick={() => void remove("player", player.id, player.name)} className="text-slate-600 hover:text-red-300"><Trash2 size={14}/></button></div>)}</div></Panel>
  </div>;
}

function Heading({ icon: Icon, title }: { icon: typeof Trophy; title: string }) { return <div className="flex items-center gap-2"><Icon size={17} className="text-cyan-300"/><h2 className="font-bold text-white">{title}</h2></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label>{label}</Label><div className="mt-1">{children}</div></div>; }
function Row({ label, active, onClick, onDelete }: { label: string; active: boolean; onClick?: () => void; onDelete: () => void }) { return <div className={`flex items-center rounded-md border ${active ? "border-cyan-300/40 bg-cyan-300/10" : "border-white/10 bg-black/10"}`}><button type="button" onClick={onClick} className="min-w-0 flex-1 truncate px-3 py-2 text-left text-sm text-white">{label}</button><button type="button" onClick={onDelete} className="p-2 text-slate-600 hover:text-red-300"><Trash2 size={13}/></button></div>; }
function PlayerPhoto({ player }: { player: Player }) { return <span className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-md bg-cyan-300/10 bg-cover bg-center text-cyan-200" style={player.photoUrl ? { backgroundImage: `url(${player.photoUrl})` } : undefined}>{!player.photoUrl ? <UserRound size={19}/> : null}</span>; }
